namespace BaristaNotes.Core.Models.Enums;

/// <summary>
/// Origin of a <see cref="Recipe"/> — how the app obtained its parameters.
/// </summary>
public enum RecipeSource
{
    /// <summary>Scraped from the roaster's own website.</summary>
    RoasterSite = 1,
    /// <summary>Generated by an AI model (fallback when no roaster recipe is found).</summary>
    AIGenerated = 2,
    /// <summary>Entered manually by the user.</summary>
    Manual = 3
}
