// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using BaristaNotes.Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BaristaNotes.Core.Data.CompiledModels;

[EntityFrameworkInternal]
public partial class BagEntityType
{
    public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
    {
        var runtimeEntityType = model.AddEntityType(
            "BaristaNotes.Core.Models.Bag",
            typeof(Bag),
            baseEntityType,
            propertyCount: 10,
            navigationCount: 2,
            foreignKeyCount: 1,
            unnamedIndexCount: 4,
            keyCount: 1);

        var id = runtimeEntityType.AddProperty(
            "Id",
            typeof(int),
            propertyInfo: typeof(Bag).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(Bag).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            valueGenerated: ValueGenerated.OnAdd,
            afterSaveBehavior: PropertySaveBehavior.Throw,
            sentinel: 0);
        id.SetGetter(
            int (Bag instance) => BagUnsafeAccessors.Id(instance),
            bool (Bag instance) => BagUnsafeAccessors.Id(instance) == 0);
        id.SetSetter(
            Bag (Bag instance, int value) =>
            {
                BagUnsafeAccessors.Id(instance) = value;
                return instance;
            });
        id.SetMaterializationSetter(
            Bag (Bag instance, int value) =>
            {
                BagUnsafeAccessors.Id(instance) = value;
                return instance;
            });
        id.SetAccessors(
            int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<int>(0) : (entry.FlaggedAsTemporary(0) && BagUnsafeAccessors.Id(((Bag)(entry.Entity))) == 0 ? entry.ReadTemporaryValue<int>(0) : BagUnsafeAccessors.Id(((Bag)(entry.Entity))))),
            int (IInternalEntry entry) => BagUnsafeAccessors.Id(((Bag)(entry.Entity))),
            int (IInternalEntry entry) => entry.ReadOriginalValue<int>(id, 0),
            int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(id, 0));
        id.SetPropertyIndexes(
            index: 0,
            originalValueIndex: 0,
            shadowIndex: -1,
            relationshipIndex: 0,
            storeGenerationIndex: 0);
        id.TypeMapping = IntTypeMapping.Default.Clone(
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "INTEGER"));
        id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));

        var beanId = runtimeEntityType.AddProperty(
            "BeanId",
            typeof(int),
            propertyInfo: typeof(Bag).GetProperty("BeanId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(Bag).GetField("<BeanId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: 0);
        beanId.SetGetter(
            int (Bag instance) => BagUnsafeAccessors.BeanId(instance),
            bool (Bag instance) => BagUnsafeAccessors.BeanId(instance) == 0);
        beanId.SetSetter(
            Bag (Bag instance, int value) =>
            {
                BagUnsafeAccessors.BeanId(instance) = value;
                return instance;
            });
        beanId.SetMaterializationSetter(
            Bag (Bag instance, int value) =>
            {
                BagUnsafeAccessors.BeanId(instance) = value;
                return instance;
            });
        beanId.SetAccessors(
            int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(1) ? entry.ReadStoreGeneratedValue<int>(1) : (entry.FlaggedAsTemporary(1) && BagUnsafeAccessors.BeanId(((Bag)(entry.Entity))) == 0 ? entry.ReadTemporaryValue<int>(1) : BagUnsafeAccessors.BeanId(((Bag)(entry.Entity))))),
            int (IInternalEntry entry) => BagUnsafeAccessors.BeanId(((Bag)(entry.Entity))),
            int (IInternalEntry entry) => entry.ReadOriginalValue<int>(beanId, 1),
            int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(beanId, 1));
        beanId.SetPropertyIndexes(
            index: 1,
            originalValueIndex: 1,
            shadowIndex: -1,
            relationshipIndex: 1,
            storeGenerationIndex: 1);
        beanId.TypeMapping = IntTypeMapping.Default.Clone(
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "INTEGER"));
        beanId.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(beanId));

        var createdAt = runtimeEntityType.AddProperty(
            "CreatedAt",
            typeof(DateTime),
            propertyInfo: typeof(Bag).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(Bag).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
        createdAt.SetGetter(
            DateTime (Bag instance) => BagUnsafeAccessors.CreatedAt(instance),
            bool (Bag instance) => BagUnsafeAccessors.CreatedAt(instance) == default(DateTime));
        createdAt.SetSetter(
            Bag (Bag instance, DateTime value) =>
            {
                BagUnsafeAccessors.CreatedAt(instance) = value;
                return instance;
            });
        createdAt.SetMaterializationSetter(
            Bag (Bag instance, DateTime value) =>
            {
                BagUnsafeAccessors.CreatedAt(instance) = value;
                return instance;
            });
        createdAt.SetAccessors(
            DateTime (IInternalEntry entry) => BagUnsafeAccessors.CreatedAt(((Bag)(entry.Entity))),
            DateTime (IInternalEntry entry) => BagUnsafeAccessors.CreatedAt(((Bag)(entry.Entity))),
            DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(createdAt, 2),
            DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(createdAt));
        createdAt.SetPropertyIndexes(
            index: 2,
            originalValueIndex: 2,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        createdAt.TypeMapping = SqliteDateTimeTypeMapping.Default;

        var isActive = runtimeEntityType.AddProperty(
            "IsActive",
            typeof(bool),
            propertyInfo: typeof(Bag).GetProperty("IsActive", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(Bag).GetField("<IsActive>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            valueGenerated: ValueGenerated.OnAdd,
            sentinel: true);
        isActive.SetGetter(
            bool (Bag instance) => BagUnsafeAccessors.IsActive(instance),
            bool (Bag instance) => BagUnsafeAccessors.IsActive(instance) == true);
        isActive.SetSetter(
            Bag (Bag instance, bool value) =>
            {
                BagUnsafeAccessors.IsActive(instance) = value;
                return instance;
            });
        isActive.SetMaterializationSetter(
            Bag (Bag instance, bool value) =>
            {
                BagUnsafeAccessors.IsActive(instance) = value;
                return instance;
            });
        isActive.SetAccessors(
            bool (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(3) ? entry.ReadStoreGeneratedValue<bool>(2) : (entry.FlaggedAsTemporary(3) && BagUnsafeAccessors.IsActive(((Bag)(entry.Entity))) == true ? entry.ReadTemporaryValue<bool>(2) : BagUnsafeAccessors.IsActive(((Bag)(entry.Entity))))),
            bool (IInternalEntry entry) => BagUnsafeAccessors.IsActive(((Bag)(entry.Entity))),
            bool (IInternalEntry entry) => entry.ReadOriginalValue<bool>(isActive, 3),
            bool (IInternalEntry entry) => entry.GetCurrentValue<bool>(isActive));
        isActive.SetPropertyIndexes(
            index: 3,
            originalValueIndex: 3,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: 2);
        isActive.TypeMapping = BoolTypeMapping.Default.Clone(
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "INTEGER"));
        isActive.AddAnnotation("Relational:DefaultValue", true);

        var isComplete = runtimeEntityType.AddProperty(
            "IsComplete",
            typeof(bool),
            propertyInfo: typeof(Bag).GetProperty("IsComplete", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(Bag).GetField("<IsComplete>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            valueGenerated: ValueGenerated.OnAdd,
            sentinel: false);
        isComplete.SetGetter(
            bool (Bag instance) => BagUnsafeAccessors.IsComplete(instance),
            bool (Bag instance) => BagUnsafeAccessors.IsComplete(instance) == false);
        isComplete.SetSetter(
            Bag (Bag instance, bool value) =>
            {
                BagUnsafeAccessors.IsComplete(instance) = value;
                return instance;
            });
        isComplete.SetMaterializationSetter(
            Bag (Bag instance, bool value) =>
            {
                BagUnsafeAccessors.IsComplete(instance) = value;
                return instance;
            });
        isComplete.SetAccessors(
            bool (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(4) ? entry.ReadStoreGeneratedValue<bool>(3) : (entry.FlaggedAsTemporary(4) && BagUnsafeAccessors.IsComplete(((Bag)(entry.Entity))) == false ? entry.ReadTemporaryValue<bool>(3) : BagUnsafeAccessors.IsComplete(((Bag)(entry.Entity))))),
            bool (IInternalEntry entry) => BagUnsafeAccessors.IsComplete(((Bag)(entry.Entity))),
            bool (IInternalEntry entry) => entry.ReadOriginalValue<bool>(isComplete, 4),
            bool (IInternalEntry entry) => entry.GetCurrentValue<bool>(isComplete));
        isComplete.SetPropertyIndexes(
            index: 4,
            originalValueIndex: 4,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: 3);
        isComplete.TypeMapping = BoolTypeMapping.Default.Clone(
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "INTEGER"));
        isComplete.AddAnnotation("Relational:DefaultValue", false);

        var isDeleted = runtimeEntityType.AddProperty(
            "IsDeleted",
            typeof(bool),
            propertyInfo: typeof(Bag).GetProperty("IsDeleted", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(Bag).GetField("<IsDeleted>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            valueGenerated: ValueGenerated.OnAdd,
            sentinel: false);
        isDeleted.SetGetter(
            bool (Bag instance) => BagUnsafeAccessors.IsDeleted(instance),
            bool (Bag instance) => BagUnsafeAccessors.IsDeleted(instance) == false);
        isDeleted.SetSetter(
            Bag (Bag instance, bool value) =>
            {
                BagUnsafeAccessors.IsDeleted(instance) = value;
                return instance;
            });
        isDeleted.SetMaterializationSetter(
            Bag (Bag instance, bool value) =>
            {
                BagUnsafeAccessors.IsDeleted(instance) = value;
                return instance;
            });
        isDeleted.SetAccessors(
            bool (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(5) ? entry.ReadStoreGeneratedValue<bool>(4) : (entry.FlaggedAsTemporary(5) && BagUnsafeAccessors.IsDeleted(((Bag)(entry.Entity))) == false ? entry.ReadTemporaryValue<bool>(4) : BagUnsafeAccessors.IsDeleted(((Bag)(entry.Entity))))),
            bool (IInternalEntry entry) => BagUnsafeAccessors.IsDeleted(((Bag)(entry.Entity))),
            bool (IInternalEntry entry) => entry.ReadOriginalValue<bool>(isDeleted, 5),
            bool (IInternalEntry entry) => entry.GetCurrentValue<bool>(isDeleted));
        isDeleted.SetPropertyIndexes(
            index: 5,
            originalValueIndex: 5,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: 4);
        isDeleted.TypeMapping = BoolTypeMapping.Default.Clone(
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "INTEGER"));
        isDeleted.AddAnnotation("Relational:DefaultValue", false);

        var lastModifiedAt = runtimeEntityType.AddProperty(
            "LastModifiedAt",
            typeof(DateTime),
            propertyInfo: typeof(Bag).GetProperty("LastModifiedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(Bag).GetField("<LastModifiedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
        lastModifiedAt.SetGetter(
            DateTime (Bag instance) => BagUnsafeAccessors.LastModifiedAt(instance),
            bool (Bag instance) => BagUnsafeAccessors.LastModifiedAt(instance) == default(DateTime));
        lastModifiedAt.SetSetter(
            Bag (Bag instance, DateTime value) =>
            {
                BagUnsafeAccessors.LastModifiedAt(instance) = value;
                return instance;
            });
        lastModifiedAt.SetMaterializationSetter(
            Bag (Bag instance, DateTime value) =>
            {
                BagUnsafeAccessors.LastModifiedAt(instance) = value;
                return instance;
            });
        lastModifiedAt.SetAccessors(
            DateTime (IInternalEntry entry) => BagUnsafeAccessors.LastModifiedAt(((Bag)(entry.Entity))),
            DateTime (IInternalEntry entry) => BagUnsafeAccessors.LastModifiedAt(((Bag)(entry.Entity))),
            DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(lastModifiedAt, 6),
            DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(lastModifiedAt));
        lastModifiedAt.SetPropertyIndexes(
            index: 6,
            originalValueIndex: 6,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        lastModifiedAt.TypeMapping = SqliteDateTimeTypeMapping.Default;

        var notes = runtimeEntityType.AddProperty(
            "Notes",
            typeof(string),
            propertyInfo: typeof(Bag).GetProperty("Notes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(Bag).GetField("<Notes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            nullable: true,
            maxLength: 500);
        notes.SetGetter(
            string (Bag instance) => BagUnsafeAccessors.Notes(instance),
            bool (Bag instance) => BagUnsafeAccessors.Notes(instance) == null);
        notes.SetSetter(
            Bag (Bag instance, string value) =>
            {
                BagUnsafeAccessors.Notes(instance) = value;
                return instance;
            });
        notes.SetMaterializationSetter(
            Bag (Bag instance, string value) =>
            {
                BagUnsafeAccessors.Notes(instance) = value;
                return instance;
            });
        notes.SetAccessors(
            string (IInternalEntry entry) => BagUnsafeAccessors.Notes(((Bag)(entry.Entity))),
            string (IInternalEntry entry) => BagUnsafeAccessors.Notes(((Bag)(entry.Entity))),
            string (IInternalEntry entry) => entry.ReadOriginalValue<string>(notes, 7),
            string (IInternalEntry entry) => entry.GetCurrentValue<string>(notes));
        notes.SetPropertyIndexes(
            index: 7,
            originalValueIndex: 7,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        notes.TypeMapping = SqliteStringTypeMapping.Default;

        var roastDate = runtimeEntityType.AddProperty(
            "RoastDate",
            typeof(DateTime),
            propertyInfo: typeof(Bag).GetProperty("RoastDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(Bag).GetField("<RoastDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
        roastDate.SetGetter(
            DateTime (Bag instance) => BagUnsafeAccessors.RoastDate(instance),
            bool (Bag instance) => BagUnsafeAccessors.RoastDate(instance) == default(DateTime));
        roastDate.SetSetter(
            Bag (Bag instance, DateTime value) =>
            {
                BagUnsafeAccessors.RoastDate(instance) = value;
                return instance;
            });
        roastDate.SetMaterializationSetter(
            Bag (Bag instance, DateTime value) =>
            {
                BagUnsafeAccessors.RoastDate(instance) = value;
                return instance;
            });
        roastDate.SetAccessors(
            DateTime (IInternalEntry entry) => BagUnsafeAccessors.RoastDate(((Bag)(entry.Entity))),
            DateTime (IInternalEntry entry) => BagUnsafeAccessors.RoastDate(((Bag)(entry.Entity))),
            DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(roastDate, 8),
            DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(roastDate));
        roastDate.SetPropertyIndexes(
            index: 8,
            originalValueIndex: 8,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        roastDate.TypeMapping = SqliteDateTimeTypeMapping.Default;

        var syncId = runtimeEntityType.AddProperty(
            "SyncId",
            typeof(Guid),
            propertyInfo: typeof(Bag).GetProperty("SyncId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(Bag).GetField("<SyncId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
        syncId.SetGetter(
            Guid (Bag instance) => BagUnsafeAccessors.SyncId(instance),
            bool (Bag instance) => BagUnsafeAccessors.SyncId(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
        syncId.SetSetter(
            Bag (Bag instance, Guid value) =>
            {
                BagUnsafeAccessors.SyncId(instance) = value;
                return instance;
            });
        syncId.SetMaterializationSetter(
            Bag (Bag instance, Guid value) =>
            {
                BagUnsafeAccessors.SyncId(instance) = value;
                return instance;
            });
        syncId.SetAccessors(
            Guid (IInternalEntry entry) => BagUnsafeAccessors.SyncId(((Bag)(entry.Entity))),
            Guid (IInternalEntry entry) => BagUnsafeAccessors.SyncId(((Bag)(entry.Entity))),
            Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(syncId, 9),
            Guid (IInternalEntry entry) => entry.GetCurrentValue<Guid>(syncId));
        syncId.SetPropertyIndexes(
            index: 9,
            originalValueIndex: 9,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        syncId.TypeMapping = SqliteGuidTypeMapping.Default;
        syncId.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(syncId));

        var key = runtimeEntityType.AddKey(
            new[] { id });
        runtimeEntityType.SetPrimaryKey(key);

        var index = runtimeEntityType.AddIndex(
            new[] { beanId });

        var index0 = runtimeEntityType.AddIndex(
            new[] { syncId },
            unique: true);

        var index1 = runtimeEntityType.AddIndex(
            new[] { beanId, roastDate });

        var index2 = runtimeEntityType.AddIndex(
            new[] { beanId, isComplete, roastDate });

        return runtimeEntityType;
    }

    public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
    {
        var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("BeanId") },
            principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
            principalEntityType,
            deleteBehavior: DeleteBehavior.Cascade,
            required: true);

        var bean = declaringEntityType.AddNavigation("Bean",
            runtimeForeignKey,
            onDependent: true,
            typeof(Bean),
            propertyInfo: typeof(Bag).GetProperty("Bean", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(Bag).GetField("<Bean>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

        bean.SetGetter(
            Bean (Bag instance) => BagUnsafeAccessors.Bean(instance),
            bool (Bag instance) => BagUnsafeAccessors.Bean(instance) == null);
        bean.SetSetter(
            Bag (Bag instance, Bean value) =>
            {
                BagUnsafeAccessors.Bean(instance) = value;
                return instance;
            });
        bean.SetMaterializationSetter(
            Bag (Bag instance, Bean value) =>
            {
                BagUnsafeAccessors.Bean(instance) = value;
                return instance;
            });
        bean.SetAccessors(
            Bean (IInternalEntry entry) => BagUnsafeAccessors.Bean(((Bag)(entry.Entity))),
            Bean (IInternalEntry entry) => BagUnsafeAccessors.Bean(((Bag)(entry.Entity))),
            null,
            Bean (IInternalEntry entry) => entry.GetCurrentValue<Bean>(bean));
        bean.SetPropertyIndexes(
            index: 0,
            originalValueIndex: -1,
            shadowIndex: -1,
            relationshipIndex: 2,
            storeGenerationIndex: -1);
        var bags = principalEntityType.AddNavigation("Bags",
            runtimeForeignKey,
            onDependent: false,
            typeof(ICollection<Bag>),
            propertyInfo: typeof(Bean).GetProperty("Bags", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(Bean).GetField("<Bags>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

        bags.SetGetter(
            ICollection<Bag> (Bean instance) => BeanUnsafeAccessors.Bags(instance),
            bool (Bean instance) => BeanUnsafeAccessors.Bags(instance) == null);
        bags.SetSetter(
            Bean (Bean instance, ICollection<Bag> value) =>
            {
                BeanUnsafeAccessors.Bags(instance) = value;
                return instance;
            });
        bags.SetMaterializationSetter(
            Bean (Bean instance, ICollection<Bag> value) =>
            {
                BeanUnsafeAccessors.Bags(instance) = value;
                return instance;
            });
        bags.SetAccessors(
            ICollection<Bag> (IInternalEntry entry) => BeanUnsafeAccessors.Bags(((Bean)(entry.Entity))),
            ICollection<Bag> (IInternalEntry entry) => BeanUnsafeAccessors.Bags(((Bean)(entry.Entity))),
            null,
            ICollection<Bag> (IInternalEntry entry) => entry.GetCurrentValue<ICollection<Bag>>(bags));
        bags.SetPropertyIndexes(
            index: 0,
            originalValueIndex: -1,
            shadowIndex: -1,
            relationshipIndex: 1,
            storeGenerationIndex: -1);
        bags.SetCollectionAccessor<Bean, ICollection<Bag>, Bag>(
            ICollection<Bag> (Bean entity) => BeanUnsafeAccessors.Bags(entity),
            (Bean entity, ICollection<Bag> collection) => BeanUnsafeAccessors.Bags(entity) = ((ICollection<Bag>)collection),
            (Bean entity, ICollection<Bag> collection) => BeanUnsafeAccessors.Bags(entity) = ((ICollection<Bag>)collection),
            ICollection<Bag> (Bean entity, Action<Bean, ICollection<Bag>> setter) => ClrCollectionAccessorFactory.CreateAndSetHashSet<Bean, ICollection<Bag>, Bag>(entity, setter),
            ICollection<Bag> () => ((ICollection<Bag>)(((ICollection<Bag>)(new HashSet<Bag>(ReferenceEqualityComparer.Instance))))));
        return runtimeForeignKey;
    }

    public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
    {
        var id = runtimeEntityType.FindProperty("Id");
        var beanId = runtimeEntityType.FindProperty("BeanId");
        var createdAt = runtimeEntityType.FindProperty("CreatedAt");
        var isActive = runtimeEntityType.FindProperty("IsActive");
        var isComplete = runtimeEntityType.FindProperty("IsComplete");
        var isDeleted = runtimeEntityType.FindProperty("IsDeleted");
        var lastModifiedAt = runtimeEntityType.FindProperty("LastModifiedAt");
        var notes = runtimeEntityType.FindProperty("Notes");
        var roastDate = runtimeEntityType.FindProperty("RoastDate");
        var syncId = runtimeEntityType.FindProperty("SyncId");
        var key = runtimeEntityType.FindKey(new[] { id });
        key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<int>(key));
        key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<int>(key));
        var bean = runtimeEntityType.FindNavigation("Bean");
        var shotRecords = runtimeEntityType.FindNavigation("ShotRecords");
        runtimeEntityType.SetOriginalValuesFactory(
            ISnapshot (IInternalEntry source) =>
            {
                var structuralType = ((Bag)(source.Entity));
                return ((ISnapshot)(new Snapshot<int, int, DateTime, bool, bool, bool, DateTime, string, DateTime, Guid>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), ((ValueComparer<int>)(((IProperty)beanId).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(beanId)), ((ValueComparer<DateTime>)(((IProperty)createdAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(createdAt)), ((ValueComparer<bool>)(((IProperty)isActive).GetValueComparer())).Snapshot(source.GetCurrentValue<bool>(isActive)), ((ValueComparer<bool>)(((IProperty)isComplete).GetValueComparer())).Snapshot(source.GetCurrentValue<bool>(isComplete)), ((ValueComparer<bool>)(((IProperty)isDeleted).GetValueComparer())).Snapshot(source.GetCurrentValue<bool>(isDeleted)), ((ValueComparer<DateTime>)(((IProperty)lastModifiedAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(lastModifiedAt)), (source.GetCurrentValue<string>(notes) == null ? null : ((ValueComparer<string>)(((IProperty)notes).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(notes))), ((ValueComparer<DateTime>)(((IProperty)roastDate).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(roastDate)), ((ValueComparer<Guid>)(((IProperty)syncId).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(syncId)))));
            });
        runtimeEntityType.SetStoreGeneratedValuesFactory(
            ISnapshot () => ((ISnapshot)(new Snapshot<int, int, bool, bool, bool>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(default(int)), ((ValueComparer<int>)(((IProperty)beanId).GetValueComparer())).Snapshot(default(int)), ((ValueComparer<bool>)(((IProperty)isActive).GetValueComparer())).Snapshot(default(bool)), ((ValueComparer<bool>)(((IProperty)isComplete).GetValueComparer())).Snapshot(default(bool)), ((ValueComparer<bool>)(((IProperty)isDeleted).GetValueComparer())).Snapshot(default(bool))))));
        runtimeEntityType.SetTemporaryValuesFactory(
            ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<int, int, bool, bool, bool>(default(int), default(int), default(bool), default(bool), default(bool)))));
        runtimeEntityType.SetShadowValuesFactory(
            ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
        runtimeEntityType.SetEmptyShadowValuesFactory(
            ISnapshot () => Snapshot.Empty);
        runtimeEntityType.SetRelationshipSnapshotFactory(
            ISnapshot (IInternalEntry source) =>
            {
                var structuralType = ((Bag)(source.Entity));
                return ((ISnapshot)(new Snapshot<int, int, object, object>(((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), ((ValueComparer<int>)(((IProperty)beanId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(beanId)), source.GetCurrentValue<Bean>(bean), SnapshotFactoryFactory.SnapshotCollection(source.GetCurrentValue<ICollection<ShotRecord>>(shotRecords)))));
            });
        runtimeEntityType.SetCounts(new PropertyCounts(
            propertyCount: 10,
            navigationCount: 2,
            complexPropertyCount: 0,
            complexCollectionCount: 0,
            originalValueCount: 10,
            shadowCount: 0,
            relationshipCount: 4,
            storeGeneratedCount: 5));
        runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
        runtimeEntityType.AddAnnotation("Relational:Schema", null);
        runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
        runtimeEntityType.AddAnnotation("Relational:TableName", "Bags");
        runtimeEntityType.AddAnnotation("Relational:ViewName", null);
        runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

        Customize(runtimeEntityType);
    }

    static partial void Customize(RuntimeEntityType runtimeEntityType);
}
