// <auto-generated />
using BaristaNotes.Core.Data;
using BaristaNotes.Core.Data.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(BaristaNotesContext), typeof(BaristaNotesContextModel))]
