// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using BaristaNotes.Core.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BaristaNotes.Core.Data.CompiledModels;

public static class BeanUnsafeAccessors
{
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
    public static extern ref int Id(Bean @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
    public static extern ref DateTime CreatedAt(Bean @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsActive>k__BackingField")]
    public static extern ref bool IsActive(Bean @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsDeleted>k__BackingField")]
    public static extern ref bool IsDeleted(Bean @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastModifiedAt>k__BackingField")]
    public static extern ref DateTime LastModifiedAt(Bean @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
    public static extern ref string Name(Bean @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Notes>k__BackingField")]
    public static extern ref string Notes(Bean @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Origin>k__BackingField")]
    public static extern ref string Origin(Bean @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Roaster>k__BackingField")]
    public static extern ref string Roaster(Bean @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RoasterUrl>k__BackingField")]
    public static extern ref string RoasterUrl(Bean @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SyncId>k__BackingField")]
    public static extern ref Guid SyncId(Bean @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Bags>k__BackingField")]
    public static extern ref ICollection<Bag> Bags(Bean @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Recipes>k__BackingField")]
    public static extern ref ICollection<Recipe> Recipes(Bean @this);
}
