// <auto-generated />

using BaristaNotes.Core.Data;
using BaristaNotes.Core.Models;
using BaristaNotes.Core.Models.Enums;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Infrastructure.Internal;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.EntityFrameworkCore.Query.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

#pragma warning disable EF9100 // Precompiled query is experimental
#nullable enable annotations

namespace Microsoft.EntityFrameworkCore.GeneratedInterceptors
{
    file static class EntityFrameworkCoreInterceptors
    {
        #region Query1

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "vvPC3WMdcz+i+uEf/r7Pn9kFAABHcmluZGVyUHJvZmlsZVJlcG9zaXRvcnkuY3M=")]
        public static global::System.Threading.Tasks.Task<TSource?> Query1_FirstOrDefaultAsync1<TSource>(this global::System.Linq.IQueryable<TSource> source, global::System.Linq.Expressions.Expression<global::System.Func<TSource,global::System.Boolean>> predicate, global::System.Threading.CancellationToken cancellationToken)
        {
            var precompiledQueryContext = new PrecompiledQueryContext<TSource>(((IInfrastructure<DbContext>)source).Instance);
            var queryContext = precompiledQueryContext.QueryContext;
            var binary1 = (BinaryExpression)predicate.Body;
            queryContext.Parameters.Add(
                "profileId",
                Expression.Lambda<Func<object?>>(Expression.Convert(binary1.Right, typeof(object)))
                .Compile(preferInterpretation: true)
                .Invoke());
            queryContext.CancellationToken = cancellationToken;
            Query1_Executor ??= Query1_GenerateExecutor(precompiledQueryContext.DbContext, precompiledQueryContext.QueryContext);
            return ((Func<QueryContext, global::System.Threading.Tasks.Task<TSource>>)(Query1_Executor))(queryContext);
        }

        private static object Query1_GenerateExecutor(DbContext dbContext, QueryContext queryContext)
        {
            var relationalModel = dbContext.Model.GetRelationalModel();
            var relationalTypeMappingSource = dbContext.GetService<IRelationalTypeMappingSource>();
            var materializerLiftableConstantContext = new RelationalMaterializerLiftableConstantContext(
                dbContext.GetService<ShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalCommandBuilderDependencies>());
            var relationalCommandTemplate = ((IRelationalCommandTemplate)(new RelationalCommand(materializerLiftableConstantContext.CommandBuilderDependencies, "SELECT \"g\".\"Id\", \"g\".\"AnchorsJson\", \"g\".\"CreatedAt\", \"g\".\"EquipmentId\", \"g\".\"IsDeleted\", \"g\".\"LastModifiedAt\", \"g\".\"MaxSetting\", \"g\".\"MinSetting\", \"g\".\"StepSize\", \"g\".\"SyncId\"\nFROM \"GrinderProfiles\" AS \"g\"\nWHERE \"g\".\"Id\" = @profileId\nLIMIT 1", "SELECT \"g\".\"Id\", \"g\".\"AnchorsJson\", \"g\".\"CreatedAt\", \"g\".\"EquipmentId\", \"g\".\"IsDeleted\", \"g\".\"LastModifiedAt\", \"g\".\"MaxSetting\", \"g\".\"MinSetting\", \"g\".\"StepSize\", \"g\".\"SyncId\"\nFROM \"GrinderProfiles\" AS \"g\"\nWHERE \"g\".\"Id\" = @profileId\nLIMIT 1", new IRelationalParameter[] { new TypeMappedRelationalParameter("profileId", "@profileId", relationalTypeMappingSource.FindMapping(typeof(int), "INTEGER", false, false, (int? )(null), false, false, (int? )(null), (int? )(null)), false, ParameterDirection.Input) })));
            var emptyValueBuffer = ValueBuffer.Empty;
            var grinderProfileEntityType = materializerLiftableConstantContext.Dependencies.Model.FindEntityType("BaristaNotes.Core.Models.GrinderProfile");
            var key = grinderProfileEntityType.FindPrimaryKey();
            var emptySnapshot = Snapshot.Empty;
            var grinderProfileEntityType0 = ((RuntimeEntityType)grinderProfileEntityType);
            return Task<GrinderProfile> (QueryContext queryContext) => ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync(SingleQueryingEnumerable.Create(((RelationalQueryContext)queryContext), IRelationalCommandTemplate (Dictionary<string, object> parameters) => relationalCommandTemplate, (ReaderColumn[])(null), GrinderProfile (QueryContext queryContext, DbDataReader dataReader, ResultContext resultContext, SingleQueryResultCoordinator resultCoordinator) =>
{
    IEntityType entityType1 = default(IEntityType);
    bool hasNullKey1 = default(bool);
    var materializationContext1 = new MaterializationContext(in emptyValueBuffer, queryContext.Context);
    var instance1 = default(GrinderProfile);
    var entry1 = queryContext.TryGetEntry(key, new object[] { ((object)(dataReader.GetInt32(0))) }, true, out hasNullKey1);
    if (!hasNullKey1)
    {
        if (entry1 != default(InternalEntityEntry))
        {
            entityType1 = entry1.EntityType;
            instance1 = ((GrinderProfile)(entry1.Entity));
        }
        else
        {
            var shadowSnapshot1 = emptySnapshot;
            entityType1 = grinderProfileEntityType;
            if (entityType1 == grinderProfileEntityType)
            {
                var instance = new GrinderProfile();
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_Id_Set(instance) = dataReader.GetInt32(0);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_AnchorsJson_Set(instance) = (dataReader.IsDBNull(1) ? default(string) : dataReader.GetString(1));
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_CreatedAt_Set(instance) = dataReader.GetDateTime(2);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_EquipmentId_Set(instance) = dataReader.GetInt32(3);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_IsDeleted_Set(instance) = dataReader.GetBoolean(4);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_LastModifiedAt_Set(instance) = dataReader.GetDateTime(5);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_MaxSetting_Set(instance) = (dataReader.IsDBNull(6) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(6))));
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_MinSetting_Set(instance) = (dataReader.IsDBNull(7) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(7))));
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_StepSize_Set(instance) = (dataReader.IsDBNull(8) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(8))));
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_SyncId_Set(instance) = dataReader.GetGuid(9);
                if (instance is IInjectableService)
                {
                    ((IInjectableService)instance).Injected(materializationContext1.Context, instance, QueryTrackingBehavior.TrackAll, grinderProfileEntityType0);
                }

                instance1 = instance;
            }
            else
            {
                instance1 = default(GrinderProfile);
            }

            entry1 = (entityType1 == default(IEntityType) ? default(InternalEntityEntry) : queryContext.StartTracking(entityType1, instance1, in shadowSnapshot1));
        }
    }

    var entity = instance1;
    return entity;
}, typeof(BaristaNotesContext), false, false, true), queryContext.CancellationToken);
        }

        private static object Query1_Executor;

        #endregion Query1
        #region Query2

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "vvPC3WMdcz+i+uEf/r7Pn24GAABHcmluZGVyUHJvZmlsZVJlcG9zaXRvcnkuY3M=")]
        public static global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<TSource>> Query2_ToListAsync1<TSource>(this global::System.Linq.IQueryable<TSource> source, global::System.Threading.CancellationToken cancellationToken)
        {
            var precompiledQueryContext = new PrecompiledQueryContext<TSource>(((IInfrastructure<DbContext>)source).Instance);
            var queryContext = precompiledQueryContext.QueryContext;
            queryContext.CancellationToken = cancellationToken;
            Query2_Executor ??= Query2_GenerateExecutor(precompiledQueryContext.DbContext, precompiledQueryContext.QueryContext);
            var queryingEnumerable = ((Func<QueryContext, IAsyncEnumerable<TSource>>)(Query2_Executor))(queryContext);
            var asyncQueryingEnumerable = new PrecompiledQueryableAsyncEnumerableAdapter<TSource>(queryingEnumerable);
            return asyncQueryingEnumerable.ToListAsync(cancellationToken);
        }

        private static object Query2_GenerateExecutor(DbContext dbContext, QueryContext queryContext)
        {
            var relationalModel = dbContext.Model.GetRelationalModel();
            var relationalTypeMappingSource = dbContext.GetService<IRelationalTypeMappingSource>();
            var materializerLiftableConstantContext = new RelationalMaterializerLiftableConstantContext(
                dbContext.GetService<ShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalCommandBuilderDependencies>());
            var relationalCommandTemplate = ((IRelationalCommandTemplate)(new RelationalCommand(materializerLiftableConstantContext.CommandBuilderDependencies, "SELECT \"g\".\"Id\", \"g\".\"AnchorsJson\", \"g\".\"CreatedAt\", \"g\".\"EquipmentId\", \"g\".\"IsDeleted\", \"g\".\"LastModifiedAt\", \"g\".\"MaxSetting\", \"g\".\"MinSetting\", \"g\".\"StepSize\", \"g\".\"SyncId\"\nFROM \"GrinderProfiles\" AS \"g\"", "SELECT \"g\".\"Id\", \"g\".\"AnchorsJson\", \"g\".\"CreatedAt\", \"g\".\"EquipmentId\", \"g\".\"IsDeleted\", \"g\".\"LastModifiedAt\", \"g\".\"MaxSetting\", \"g\".\"MinSetting\", \"g\".\"StepSize\", \"g\".\"SyncId\"\nFROM \"GrinderProfiles\" AS \"g\"", new IRelationalParameter[] { })));
            var emptyValueBuffer = ValueBuffer.Empty;
            var grinderProfileEntityType = materializerLiftableConstantContext.Dependencies.Model.FindEntityType("BaristaNotes.Core.Models.GrinderProfile");
            var key = grinderProfileEntityType.FindPrimaryKey();
            var emptySnapshot = Snapshot.Empty;
            var grinderProfileEntityType0 = ((RuntimeEntityType)grinderProfileEntityType);
            return IAsyncEnumerable<GrinderProfile> (QueryContext queryContext) => SingleQueryingEnumerable.Create(((RelationalQueryContext)queryContext), IRelationalCommandTemplate (Dictionary<string, object> parameters) => relationalCommandTemplate, (ReaderColumn[])(null), GrinderProfile (QueryContext queryContext, DbDataReader dataReader, ResultContext resultContext, SingleQueryResultCoordinator resultCoordinator) =>
{
    IEntityType entityType1 = default(IEntityType);
    bool hasNullKey1 = default(bool);
    var materializationContext1 = new MaterializationContext(in emptyValueBuffer, queryContext.Context);
    var instance1 = default(GrinderProfile);
    var entry1 = queryContext.TryGetEntry(key, new object[] { ((object)(dataReader.GetInt32(0))) }, true, out hasNullKey1);
    if (!hasNullKey1)
    {
        if (entry1 != default(InternalEntityEntry))
        {
            entityType1 = entry1.EntityType;
            instance1 = ((GrinderProfile)(entry1.Entity));
        }
        else
        {
            var shadowSnapshot1 = emptySnapshot;
            entityType1 = grinderProfileEntityType;
            if (entityType1 == grinderProfileEntityType)
            {
                var instance = new GrinderProfile();
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_Id_Set(instance) = dataReader.GetInt32(0);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_AnchorsJson_Set(instance) = (dataReader.IsDBNull(1) ? default(string) : dataReader.GetString(1));
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_CreatedAt_Set(instance) = dataReader.GetDateTime(2);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_EquipmentId_Set(instance) = dataReader.GetInt32(3);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_IsDeleted_Set(instance) = dataReader.GetBoolean(4);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_LastModifiedAt_Set(instance) = dataReader.GetDateTime(5);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_MaxSetting_Set(instance) = (dataReader.IsDBNull(6) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(6))));
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_MinSetting_Set(instance) = (dataReader.IsDBNull(7) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(7))));
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_StepSize_Set(instance) = (dataReader.IsDBNull(8) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(8))));
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_SyncId_Set(instance) = dataReader.GetGuid(9);
                if (instance is IInjectableService)
                {
                    ((IInjectableService)instance).Injected(materializationContext1.Context, instance, QueryTrackingBehavior.TrackAll, grinderProfileEntityType0);
                }

                instance1 = instance;
            }
            else
            {
                instance1 = default(GrinderProfile);
            }

            entry1 = (entityType1 == default(IEntityType) ? default(InternalEntityEntry) : queryContext.StartTracking(entityType1, instance1, in shadowSnapshot1));
        }
    }

    var entity = instance1;
    return entity;
}, typeof(BaristaNotesContext), false, false, true);
        }

        private static object Query2_Executor;

        #endregion Query2
        #region Query3

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "vvPC3WMdcz+i+uEf/r7PnzoHAABHcmluZGVyUHJvZmlsZVJlcG9zaXRvcnkuY3M=")]
        public static global::System.Linq.IQueryable<TEntity> Query3_AsNoTracking1<TEntity>(this global::System.Linq.IQueryable<TEntity> source)
        where TEntity : class
        {
            var precompiledQueryContext = new PrecompiledQueryContext<TEntity>(((IInfrastructure<DbContext>)source).Instance);
            return precompiledQueryContext;
        }

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "vvPC3WMdcz+i+uEf/r7Pn1YHAABHcmluZGVyUHJvZmlsZVJlcG9zaXRvcnkuY3M=")]
        public static global::Microsoft.EntityFrameworkCore.Query.IIncludableQueryable<TEntity,TProperty> Query3_Include2<TEntity, TProperty>(this global::System.Linq.IQueryable<TEntity> source, global::System.Linq.Expressions.Expression<global::System.Func<TEntity,TProperty>> navigationPropertyPath)
        where TEntity : class
        {
            var precompiledQueryContext = (PrecompiledQueryContext<TEntity>)source;
            return precompiledQueryContext.ToIncludable<TProperty>();
        }

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "vvPC3WMdcz+i+uEf/r7Pn30HAABHcmluZGVyUHJvZmlsZVJlcG9zaXRvcnkuY3M=")]
        public static global::System.Threading.Tasks.Task<TSource?> Query3_FirstOrDefaultAsync3<TSource>(this global::System.Linq.IQueryable<TSource> source, global::System.Linq.Expressions.Expression<global::System.Func<TSource,global::System.Boolean>> predicate, global::System.Threading.CancellationToken cancellationToken)
        {
            var precompiledQueryContext = (PrecompiledQueryContext<TSource>)source;
            var queryContext = precompiledQueryContext.QueryContext;
            var binary1 = (BinaryExpression)predicate.Body;
            var binary2 = (BinaryExpression)binary1.Left;
            queryContext.Parameters.Add(
                "targetEquipmentId",
                Expression.Lambda<Func<object?>>(Expression.Convert(binary2.Right, typeof(object)))
                .Compile(preferInterpretation: true)
                .Invoke());
            queryContext.CancellationToken = cancellationToken;
            Query3_Executor ??= Query3_GenerateExecutor(precompiledQueryContext.DbContext, precompiledQueryContext.QueryContext);
            return ((Func<QueryContext, global::System.Threading.Tasks.Task<TSource>>)(Query3_Executor))(queryContext);
        }

        private static object Query3_GenerateExecutor(DbContext dbContext, QueryContext queryContext)
        {
            var relationalModel = dbContext.Model.GetRelationalModel();
            var relationalTypeMappingSource = dbContext.GetService<IRelationalTypeMappingSource>();
            var materializerLiftableConstantContext = new RelationalMaterializerLiftableConstantContext(
                dbContext.GetService<ShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalCommandBuilderDependencies>());
            var relationalCommandTemplate = ((IRelationalCommandTemplate)(new RelationalCommand(materializerLiftableConstantContext.CommandBuilderDependencies, "SELECT \"g\".\"Id\", \"g\".\"AnchorsJson\", \"g\".\"CreatedAt\", \"g\".\"EquipmentId\", \"g\".\"IsDeleted\", \"g\".\"LastModifiedAt\", \"g\".\"MaxSetting\", \"g\".\"MinSetting\", \"g\".\"StepSize\", \"g\".\"SyncId\", \"e\".\"Id\", \"e\".\"CreatedAt\", \"e\".\"IsActive\", \"e\".\"IsDeleted\", \"e\".\"LastModifiedAt\", \"e\".\"Name\", \"e\".\"Notes\", \"e\".\"SyncId\", \"e\".\"Type\"\nFROM \"GrinderProfiles\" AS \"g\"\nINNER JOIN \"Equipment\" AS \"e\" ON \"g\".\"EquipmentId\" = \"e\".\"Id\"\nWHERE \"g\".\"EquipmentId\" = @targetEquipmentId AND NOT (\"g\".\"IsDeleted\")\nLIMIT 1", "SELECT \"g\".\"Id\", \"g\".\"AnchorsJson\", \"g\".\"CreatedAt\", \"g\".\"EquipmentId\", \"g\".\"IsDeleted\", \"g\".\"LastModifiedAt\", \"g\".\"MaxSetting\", \"g\".\"MinSetting\", \"g\".\"StepSize\", \"g\".\"SyncId\", \"e\".\"Id\", \"e\".\"CreatedAt\", \"e\".\"IsActive\", \"e\".\"IsDeleted\", \"e\".\"LastModifiedAt\", \"e\".\"Name\", \"e\".\"Notes\", \"e\".\"SyncId\", \"e\".\"Type\"\nFROM \"GrinderProfiles\" AS \"g\"\nINNER JOIN \"Equipment\" AS \"e\" ON \"g\".\"EquipmentId\" = \"e\".\"Id\"\nWHERE \"g\".\"EquipmentId\" = @targetEquipmentId AND NOT (\"g\".\"IsDeleted\")\nLIMIT 1", new IRelationalParameter[] { new TypeMappedRelationalParameter("targetEquipmentId", "@targetEquipmentId", relationalTypeMappingSource.FindMapping(typeof(int), "INTEGER", false, false, (int? )(null), false, false, (int? )(null), (int? )(null)), false, ParameterDirection.Input) })));
            var emptyValueBuffer = ValueBuffer.Empty;
            var emptySnapshot = Snapshot.Empty;
            var model = materializerLiftableConstantContext.Dependencies.Model;
            var grinderProfileEntityType = model.FindEntityType("BaristaNotes.Core.Models.GrinderProfile");
            var grinderProfileEntityType0 = ((RuntimeEntityType)grinderProfileEntityType);
            var unknown = grinderProfileEntityType.FindPrimaryKey().Properties;
            var equipmentEntityType = model.FindEntityType("BaristaNotes.Core.Models.Equipment");
            var typeProperty = ((IPropertyBase)(((ITypeBase)equipmentEntityType).FindProperty("Type")));
            var equipmentEntityType0 = ((RuntimeEntityType)equipmentEntityType);
            var unknown0 = equipmentEntityType.FindPrimaryKey().Properties;
            var equipmentNavigation = grinderProfileEntityType.FindNavigation("Equipment");
            return Task<GrinderProfile> (QueryContext queryContext) => ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync(SingleQueryingEnumerable.Create(((RelationalQueryContext)queryContext), IRelationalCommandTemplate (Dictionary<string, object> parameters) => relationalCommandTemplate, (ReaderColumn[])(null), GrinderProfile (QueryContext queryContext, DbDataReader dataReader, ResultContext resultContext, SingleQueryResultCoordinator resultCoordinator) =>
{
    IEntityType entityType1 = default(IEntityType);
    IEntityType entityType2 = default(IEntityType);
    var materializationContext1 = new MaterializationContext(in emptyValueBuffer, queryContext.Context);
    var instance1 = default(GrinderProfile);
    if (((object)(dataReader.GetInt32(0))) != null)
    {
        var shadowSnapshot1 = emptySnapshot;
        entityType1 = grinderProfileEntityType;
        if (entityType1 == grinderProfileEntityType)
        {
            var instance = new GrinderProfile();
            UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_Id_Set(instance) = dataReader.GetInt32(0);
            UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_AnchorsJson_Set(instance) = (dataReader.IsDBNull(1) ? default(string) : dataReader.GetString(1));
            UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_CreatedAt_Set(instance) = dataReader.GetDateTime(2);
            UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_EquipmentId_Set(instance) = dataReader.GetInt32(3);
            UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_IsDeleted_Set(instance) = dataReader.GetBoolean(4);
            UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_LastModifiedAt_Set(instance) = dataReader.GetDateTime(5);
            UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_MaxSetting_Set(instance) = (dataReader.IsDBNull(6) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(6))));
            UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_MinSetting_Set(instance) = (dataReader.IsDBNull(7) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(7))));
            UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_StepSize_Set(instance) = (dataReader.IsDBNull(8) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(8))));
            UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_SyncId_Set(instance) = dataReader.GetGuid(9);
            if (instance is IInjectableService)
            {
                ((IInjectableService)instance).Injected(materializationContext1.Context, instance, QueryTrackingBehavior.NoTracking, grinderProfileEntityType0);
            }

            instance1 = instance;
        }
        else
        {
            instance1 = default(GrinderProfile);
        }
    }
    else
    {
        var keyValues1 = new object[]
        {
            ((object)(dataReader.GetInt32(0)))
        };
        ShapedQueryCompilingExpressionVisitor.CreateNullKeyValueInNoTrackingQuery(grinderProfileEntityType, unknown, keyValues1);
    }

    var entity = instance1;
    var materializationContext2 = new MaterializationContext(in emptyValueBuffer, queryContext.Context);
    var instance2 = default(Equipment);
    if (((object)(dataReader.GetInt32(10))) != null)
    {
        var shadowSnapshot2 = emptySnapshot;
        entityType2 = equipmentEntityType;
        if (entityType2 == equipmentEntityType)
        {
            var instance = new Equipment();
            UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Id_Set(instance) = dataReader.GetInt32(10);
            UnsafeAccessor_BaristaNotes_Core_Models_Equipment_CreatedAt_Set(instance) = dataReader.GetDateTime(11);
            UnsafeAccessor_BaristaNotes_Core_Models_Equipment_IsActive_Set(instance) = dataReader.GetBoolean(12);
            UnsafeAccessor_BaristaNotes_Core_Models_Equipment_IsDeleted_Set(instance) = dataReader.GetBoolean(13);
            UnsafeAccessor_BaristaNotes_Core_Models_Equipment_LastModifiedAt_Set(instance) = dataReader.GetDateTime(14);
            UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Name_Set(instance) = dataReader.GetString(15);
            UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Notes_Set(instance) = (dataReader.IsDBNull(16) ? default(string) : dataReader.GetString(16));
            UnsafeAccessor_BaristaNotes_Core_Models_Equipment_SyncId_Set(instance) = dataReader.GetGuid(17);
            UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Type_Set(instance) = ((EnumToNumberConverter<EquipmentType, int>)(((IReadOnlyProperty)typeProperty).GetTypeMapping().Converter)).ConvertFromProviderTyped(dataReader.GetInt32(18));
            if (instance is IInjectableService)
            {
                ((IInjectableService)instance).Injected(materializationContext2.Context, instance, QueryTrackingBehavior.NoTracking, equipmentEntityType0);
            }

            instance2 = instance;
        }
        else
        {
            instance2 = default(Equipment);
        }
    }
    else
    {
        var keyValues2 = new object[]
        {
            ((object)(dataReader.GetInt32(10)))
        };
        ShapedQueryCompilingExpressionVisitor.CreateNullKeyValueInNoTrackingQuery(equipmentEntityType, unknown0, keyValues2);
    }

    var entity0 = instance2;
    RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.IncludeReference(queryContext, entity, entity0, equipmentNavigation, default(INavigation), (GrinderProfile unnamed1, Equipment unnamed2) =>
    {
        UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_Equipment_Set(unnamed1) = unnamed2;
    }, false);
    return entity;
}, typeof(BaristaNotesContext), false, false, true), queryContext.CancellationToken);
        }

        private static object Query3_Executor;

        #endregion Query3
        #region Query4

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "vvPC3WMdcz+i+uEf/r7Pn6EIAABHcmluZGVyUHJvZmlsZVJlcG9zaXRvcnkuY3M=")]
        public static global::Microsoft.EntityFrameworkCore.Query.IIncludableQueryable<TEntity,TProperty> Query4_Include1<TEntity, TProperty>(this global::System.Linq.IQueryable<TEntity> source, global::System.Linq.Expressions.Expression<global::System.Func<TEntity,TProperty>> navigationPropertyPath)
        where TEntity : class
        {
            var precompiledQueryContext = new PrecompiledQueryContext<TEntity>(((IInfrastructure<DbContext>)source).Instance);
            return precompiledQueryContext.ToIncludable<TProperty>();
        }

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "vvPC3WMdcz+i+uEf/r7Pn8gIAABHcmluZGVyUHJvZmlsZVJlcG9zaXRvcnkuY3M=")]
        public static global::System.Threading.Tasks.Task<TSource?> Query4_FirstOrDefaultAsync2<TSource>(this global::System.Linq.IQueryable<TSource> source, global::System.Linq.Expressions.Expression<global::System.Func<TSource,global::System.Boolean>> predicate, global::System.Threading.CancellationToken cancellationToken)
        {
            var precompiledQueryContext = (PrecompiledQueryContext<TSource>)source;
            var queryContext = precompiledQueryContext.QueryContext;
            var binary1 = (BinaryExpression)predicate.Body;
            var binary2 = (BinaryExpression)binary1.Left;
            queryContext.Parameters.Add(
                "targetEquipmentId",
                Expression.Lambda<Func<object?>>(Expression.Convert(binary2.Right, typeof(object)))
                .Compile(preferInterpretation: true)
                .Invoke());
            queryContext.CancellationToken = cancellationToken;
            Query4_Executor ??= Query4_GenerateExecutor(precompiledQueryContext.DbContext, precompiledQueryContext.QueryContext);
            return ((Func<QueryContext, global::System.Threading.Tasks.Task<TSource>>)(Query4_Executor))(queryContext);
        }

        private static object Query4_GenerateExecutor(DbContext dbContext, QueryContext queryContext)
        {
            var relationalModel = dbContext.Model.GetRelationalModel();
            var relationalTypeMappingSource = dbContext.GetService<IRelationalTypeMappingSource>();
            var materializerLiftableConstantContext = new RelationalMaterializerLiftableConstantContext(
                dbContext.GetService<ShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalCommandBuilderDependencies>());
            var relationalCommandTemplate = ((IRelationalCommandTemplate)(new RelationalCommand(materializerLiftableConstantContext.CommandBuilderDependencies, "SELECT \"g\".\"Id\", \"g\".\"AnchorsJson\", \"g\".\"CreatedAt\", \"g\".\"EquipmentId\", \"g\".\"IsDeleted\", \"g\".\"LastModifiedAt\", \"g\".\"MaxSetting\", \"g\".\"MinSetting\", \"g\".\"StepSize\", \"g\".\"SyncId\", \"e\".\"Id\", \"e\".\"CreatedAt\", \"e\".\"IsActive\", \"e\".\"IsDeleted\", \"e\".\"LastModifiedAt\", \"e\".\"Name\", \"e\".\"Notes\", \"e\".\"SyncId\", \"e\".\"Type\"\nFROM \"GrinderProfiles\" AS \"g\"\nINNER JOIN \"Equipment\" AS \"e\" ON \"g\".\"EquipmentId\" = \"e\".\"Id\"\nWHERE \"g\".\"EquipmentId\" = @targetEquipmentId AND NOT (\"g\".\"IsDeleted\")\nLIMIT 1", "SELECT \"g\".\"Id\", \"g\".\"AnchorsJson\", \"g\".\"CreatedAt\", \"g\".\"EquipmentId\", \"g\".\"IsDeleted\", \"g\".\"LastModifiedAt\", \"g\".\"MaxSetting\", \"g\".\"MinSetting\", \"g\".\"StepSize\", \"g\".\"SyncId\", \"e\".\"Id\", \"e\".\"CreatedAt\", \"e\".\"IsActive\", \"e\".\"IsDeleted\", \"e\".\"LastModifiedAt\", \"e\".\"Name\", \"e\".\"Notes\", \"e\".\"SyncId\", \"e\".\"Type\"\nFROM \"GrinderProfiles\" AS \"g\"\nINNER JOIN \"Equipment\" AS \"e\" ON \"g\".\"EquipmentId\" = \"e\".\"Id\"\nWHERE \"g\".\"EquipmentId\" = @targetEquipmentId AND NOT (\"g\".\"IsDeleted\")\nLIMIT 1", new IRelationalParameter[] { new TypeMappedRelationalParameter("targetEquipmentId", "@targetEquipmentId", relationalTypeMappingSource.FindMapping(typeof(int), "INTEGER", false, false, (int? )(null), false, false, (int? )(null), (int? )(null)), false, ParameterDirection.Input) })));
            var emptyValueBuffer = ValueBuffer.Empty;
            var model = materializerLiftableConstantContext.Dependencies.Model;
            var grinderProfileEntityType = model.FindEntityType("BaristaNotes.Core.Models.GrinderProfile");
            var key = grinderProfileEntityType.FindPrimaryKey();
            var emptySnapshot = Snapshot.Empty;
            var grinderProfileEntityType0 = ((RuntimeEntityType)grinderProfileEntityType);
            var equipmentEntityType = model.FindEntityType("BaristaNotes.Core.Models.Equipment");
            var key0 = equipmentEntityType.FindPrimaryKey();
            var typeProperty = ((IPropertyBase)(((ITypeBase)equipmentEntityType).FindProperty("Type")));
            var equipmentEntityType0 = ((RuntimeEntityType)equipmentEntityType);
            var equipmentNavigation = grinderProfileEntityType.FindNavigation("Equipment");
            return Task<GrinderProfile> (QueryContext queryContext) => ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync(SingleQueryingEnumerable.Create(((RelationalQueryContext)queryContext), IRelationalCommandTemplate (Dictionary<string, object> parameters) => relationalCommandTemplate, (ReaderColumn[])(null), GrinderProfile (QueryContext queryContext, DbDataReader dataReader, ResultContext resultContext, SingleQueryResultCoordinator resultCoordinator) =>
{
    IEntityType entityType1 = default(IEntityType);
    bool hasNullKey1 = default(bool);
    IEntityType entityType2 = default(IEntityType);
    bool hasNullKey2 = default(bool);
    var materializationContext1 = new MaterializationContext(in emptyValueBuffer, queryContext.Context);
    var instance1 = default(GrinderProfile);
    var entry1 = queryContext.TryGetEntry(key, new object[] { ((object)(dataReader.GetInt32(0))) }, true, out hasNullKey1);
    if (!hasNullKey1)
    {
        if (entry1 != default(InternalEntityEntry))
        {
            entityType1 = entry1.EntityType;
            instance1 = ((GrinderProfile)(entry1.Entity));
        }
        else
        {
            var shadowSnapshot1 = emptySnapshot;
            entityType1 = grinderProfileEntityType;
            if (entityType1 == grinderProfileEntityType)
            {
                var instance = new GrinderProfile();
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_Id_Set(instance) = dataReader.GetInt32(0);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_AnchorsJson_Set(instance) = (dataReader.IsDBNull(1) ? default(string) : dataReader.GetString(1));
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_CreatedAt_Set(instance) = dataReader.GetDateTime(2);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_EquipmentId_Set(instance) = dataReader.GetInt32(3);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_IsDeleted_Set(instance) = dataReader.GetBoolean(4);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_LastModifiedAt_Set(instance) = dataReader.GetDateTime(5);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_MaxSetting_Set(instance) = (dataReader.IsDBNull(6) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(6))));
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_MinSetting_Set(instance) = (dataReader.IsDBNull(7) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(7))));
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_StepSize_Set(instance) = (dataReader.IsDBNull(8) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(8))));
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_SyncId_Set(instance) = dataReader.GetGuid(9);
                if (instance is IInjectableService)
                {
                    ((IInjectableService)instance).Injected(materializationContext1.Context, instance, QueryTrackingBehavior.TrackAll, grinderProfileEntityType0);
                }

                instance1 = instance;
            }
            else
            {
                instance1 = default(GrinderProfile);
            }

            entry1 = (entityType1 == default(IEntityType) ? default(InternalEntityEntry) : queryContext.StartTracking(entityType1, instance1, in shadowSnapshot1));
        }
    }

    var entity = instance1;
    var materializationContext2 = new MaterializationContext(in emptyValueBuffer, queryContext.Context);
    var instance2 = default(Equipment);
    var entry2 = queryContext.TryGetEntry(key0, new object[] { ((object)(dataReader.GetInt32(10))) }, true, out hasNullKey2);
    if (!hasNullKey2)
    {
        if (entry2 != default(InternalEntityEntry))
        {
            entityType2 = entry2.EntityType;
            instance2 = ((Equipment)(entry2.Entity));
        }
        else
        {
            var shadowSnapshot2 = emptySnapshot;
            entityType2 = equipmentEntityType;
            if (entityType2 == equipmentEntityType)
            {
                var instance = new Equipment();
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Id_Set(instance) = dataReader.GetInt32(10);
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_CreatedAt_Set(instance) = dataReader.GetDateTime(11);
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_IsActive_Set(instance) = dataReader.GetBoolean(12);
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_IsDeleted_Set(instance) = dataReader.GetBoolean(13);
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_LastModifiedAt_Set(instance) = dataReader.GetDateTime(14);
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Name_Set(instance) = dataReader.GetString(15);
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Notes_Set(instance) = (dataReader.IsDBNull(16) ? default(string) : dataReader.GetString(16));
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_SyncId_Set(instance) = dataReader.GetGuid(17);
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Type_Set(instance) = ((EnumToNumberConverter<EquipmentType, int>)(((IReadOnlyProperty)typeProperty).GetTypeMapping().Converter)).ConvertFromProviderTyped(dataReader.GetInt32(18));
                if (instance is IInjectableService)
                {
                    ((IInjectableService)instance).Injected(materializationContext2.Context, instance, QueryTrackingBehavior.TrackAll, equipmentEntityType0);
                }

                instance2 = instance;
            }
            else
            {
                instance2 = default(Equipment);
            }

            entry2 = (entityType2 == default(IEntityType) ? default(InternalEntityEntry) : queryContext.StartTracking(entityType2, instance2, in shadowSnapshot2));
        }
    }

    var entity0 = instance2;
    RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.IncludeReference(queryContext, entity, entity0, equipmentNavigation, default(INavigation), (GrinderProfile unnamed1, Equipment unnamed2) =>
    {
        UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_Equipment_Set(unnamed1) = unnamed2;
    }, true);
    return entity;
}, typeof(BaristaNotesContext), false, false, true), queryContext.CancellationToken);
        }

        private static object Query4_Executor;

        #endregion Query4
        #region Query5

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "vvPC3WMdcz+i+uEf/r7Pn78NAABHcmluZGVyUHJvZmlsZVJlcG9zaXRvcnkuY3M=")]
        public static global::Microsoft.EntityFrameworkCore.Query.IIncludableQueryable<TEntity,TProperty> Query5_Include1<TEntity, TProperty>(this global::System.Linq.IQueryable<TEntity> source, global::System.Linq.Expressions.Expression<global::System.Func<TEntity,TProperty>> navigationPropertyPath)
        where TEntity : class
        {
            var precompiledQueryContext = new PrecompiledQueryContext<TEntity>(((IInfrastructure<DbContext>)source).Instance);
            return precompiledQueryContext.ToIncludable<TProperty>();
        }

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "vvPC3WMdcz+i+uEf/r7Pn+oNAABHcmluZGVyUHJvZmlsZVJlcG9zaXRvcnkuY3M=")]
        public static global::System.Threading.Tasks.Task<TSource?> Query5_FirstOrDefaultAsync2<TSource>(this global::System.Linq.IQueryable<TSource> source, global::System.Linq.Expressions.Expression<global::System.Func<TSource,global::System.Boolean>> predicate, global::System.Threading.CancellationToken cancellationToken)
        {
            var precompiledQueryContext = (PrecompiledQueryContext<TSource>)source;
            var queryContext = precompiledQueryContext.QueryContext;
            var binary1 = (BinaryExpression)predicate.Body;
            var binary2 = (BinaryExpression)binary1.Left;
            queryContext.Parameters.Add(
                "targetEquipmentId",
                Expression.Lambda<Func<object?>>(Expression.Convert(binary2.Right, typeof(object)))
                .Compile(preferInterpretation: true)
                .Invoke());
            queryContext.CancellationToken = cancellationToken;
            Query5_Executor ??= Query5_GenerateExecutor(precompiledQueryContext.DbContext, precompiledQueryContext.QueryContext);
            return ((Func<QueryContext, global::System.Threading.Tasks.Task<TSource>>)(Query5_Executor))(queryContext);
        }

        private static object Query5_GenerateExecutor(DbContext dbContext, QueryContext queryContext)
        {
            var relationalModel = dbContext.Model.GetRelationalModel();
            var relationalTypeMappingSource = dbContext.GetService<IRelationalTypeMappingSource>();
            var materializerLiftableConstantContext = new RelationalMaterializerLiftableConstantContext(
                dbContext.GetService<ShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalCommandBuilderDependencies>());
            var relationalCommandTemplate = ((IRelationalCommandTemplate)(new RelationalCommand(materializerLiftableConstantContext.CommandBuilderDependencies, "SELECT \"g\".\"Id\", \"g\".\"AnchorsJson\", \"g\".\"CreatedAt\", \"g\".\"EquipmentId\", \"g\".\"IsDeleted\", \"g\".\"LastModifiedAt\", \"g\".\"MaxSetting\", \"g\".\"MinSetting\", \"g\".\"StepSize\", \"g\".\"SyncId\", \"e\".\"Id\", \"e\".\"CreatedAt\", \"e\".\"IsActive\", \"e\".\"IsDeleted\", \"e\".\"LastModifiedAt\", \"e\".\"Name\", \"e\".\"Notes\", \"e\".\"SyncId\", \"e\".\"Type\"\nFROM \"GrinderProfiles\" AS \"g\"\nINNER JOIN \"Equipment\" AS \"e\" ON \"g\".\"EquipmentId\" = \"e\".\"Id\"\nWHERE \"g\".\"EquipmentId\" = @targetEquipmentId AND NOT (\"g\".\"IsDeleted\")\nLIMIT 1", "SELECT \"g\".\"Id\", \"g\".\"AnchorsJson\", \"g\".\"CreatedAt\", \"g\".\"EquipmentId\", \"g\".\"IsDeleted\", \"g\".\"LastModifiedAt\", \"g\".\"MaxSetting\", \"g\".\"MinSetting\", \"g\".\"StepSize\", \"g\".\"SyncId\", \"e\".\"Id\", \"e\".\"CreatedAt\", \"e\".\"IsActive\", \"e\".\"IsDeleted\", \"e\".\"LastModifiedAt\", \"e\".\"Name\", \"e\".\"Notes\", \"e\".\"SyncId\", \"e\".\"Type\"\nFROM \"GrinderProfiles\" AS \"g\"\nINNER JOIN \"Equipment\" AS \"e\" ON \"g\".\"EquipmentId\" = \"e\".\"Id\"\nWHERE \"g\".\"EquipmentId\" = @targetEquipmentId AND NOT (\"g\".\"IsDeleted\")\nLIMIT 1", new IRelationalParameter[] { new TypeMappedRelationalParameter("targetEquipmentId", "@targetEquipmentId", relationalTypeMappingSource.FindMapping(typeof(int), "INTEGER", false, false, (int? )(null), false, false, (int? )(null), (int? )(null)), false, ParameterDirection.Input) })));
            var emptyValueBuffer = ValueBuffer.Empty;
            var model = materializerLiftableConstantContext.Dependencies.Model;
            var grinderProfileEntityType = model.FindEntityType("BaristaNotes.Core.Models.GrinderProfile");
            var key = grinderProfileEntityType.FindPrimaryKey();
            var emptySnapshot = Snapshot.Empty;
            var grinderProfileEntityType0 = ((RuntimeEntityType)grinderProfileEntityType);
            var equipmentEntityType = model.FindEntityType("BaristaNotes.Core.Models.Equipment");
            var key0 = equipmentEntityType.FindPrimaryKey();
            var typeProperty = ((IPropertyBase)(((ITypeBase)equipmentEntityType).FindProperty("Type")));
            var equipmentEntityType0 = ((RuntimeEntityType)equipmentEntityType);
            var equipmentNavigation = grinderProfileEntityType.FindNavigation("Equipment");
            return Task<GrinderProfile> (QueryContext queryContext) => ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync(SingleQueryingEnumerable.Create(((RelationalQueryContext)queryContext), IRelationalCommandTemplate (Dictionary<string, object> parameters) => relationalCommandTemplate, (ReaderColumn[])(null), GrinderProfile (QueryContext queryContext, DbDataReader dataReader, ResultContext resultContext, SingleQueryResultCoordinator resultCoordinator) =>
{
    IEntityType entityType1 = default(IEntityType);
    bool hasNullKey1 = default(bool);
    IEntityType entityType2 = default(IEntityType);
    bool hasNullKey2 = default(bool);
    var materializationContext1 = new MaterializationContext(in emptyValueBuffer, queryContext.Context);
    var instance1 = default(GrinderProfile);
    var entry1 = queryContext.TryGetEntry(key, new object[] { ((object)(dataReader.GetInt32(0))) }, true, out hasNullKey1);
    if (!hasNullKey1)
    {
        if (entry1 != default(InternalEntityEntry))
        {
            entityType1 = entry1.EntityType;
            instance1 = ((GrinderProfile)(entry1.Entity));
        }
        else
        {
            var shadowSnapshot1 = emptySnapshot;
            entityType1 = grinderProfileEntityType;
            if (entityType1 == grinderProfileEntityType)
            {
                var instance = new GrinderProfile();
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_Id_Set(instance) = dataReader.GetInt32(0);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_AnchorsJson_Set(instance) = (dataReader.IsDBNull(1) ? default(string) : dataReader.GetString(1));
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_CreatedAt_Set(instance) = dataReader.GetDateTime(2);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_EquipmentId_Set(instance) = dataReader.GetInt32(3);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_IsDeleted_Set(instance) = dataReader.GetBoolean(4);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_LastModifiedAt_Set(instance) = dataReader.GetDateTime(5);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_MaxSetting_Set(instance) = (dataReader.IsDBNull(6) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(6))));
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_MinSetting_Set(instance) = (dataReader.IsDBNull(7) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(7))));
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_StepSize_Set(instance) = (dataReader.IsDBNull(8) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(8))));
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_SyncId_Set(instance) = dataReader.GetGuid(9);
                if (instance is IInjectableService)
                {
                    ((IInjectableService)instance).Injected(materializationContext1.Context, instance, QueryTrackingBehavior.TrackAll, grinderProfileEntityType0);
                }

                instance1 = instance;
            }
            else
            {
                instance1 = default(GrinderProfile);
            }

            entry1 = (entityType1 == default(IEntityType) ? default(InternalEntityEntry) : queryContext.StartTracking(entityType1, instance1, in shadowSnapshot1));
        }
    }

    var entity = instance1;
    var materializationContext2 = new MaterializationContext(in emptyValueBuffer, queryContext.Context);
    var instance2 = default(Equipment);
    var entry2 = queryContext.TryGetEntry(key0, new object[] { ((object)(dataReader.GetInt32(10))) }, true, out hasNullKey2);
    if (!hasNullKey2)
    {
        if (entry2 != default(InternalEntityEntry))
        {
            entityType2 = entry2.EntityType;
            instance2 = ((Equipment)(entry2.Entity));
        }
        else
        {
            var shadowSnapshot2 = emptySnapshot;
            entityType2 = equipmentEntityType;
            if (entityType2 == equipmentEntityType)
            {
                var instance = new Equipment();
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Id_Set(instance) = dataReader.GetInt32(10);
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_CreatedAt_Set(instance) = dataReader.GetDateTime(11);
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_IsActive_Set(instance) = dataReader.GetBoolean(12);
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_IsDeleted_Set(instance) = dataReader.GetBoolean(13);
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_LastModifiedAt_Set(instance) = dataReader.GetDateTime(14);
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Name_Set(instance) = dataReader.GetString(15);
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Notes_Set(instance) = (dataReader.IsDBNull(16) ? default(string) : dataReader.GetString(16));
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_SyncId_Set(instance) = dataReader.GetGuid(17);
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Type_Set(instance) = ((EnumToNumberConverter<EquipmentType, int>)(((IReadOnlyProperty)typeProperty).GetTypeMapping().Converter)).ConvertFromProviderTyped(dataReader.GetInt32(18));
                if (instance is IInjectableService)
                {
                    ((IInjectableService)instance).Injected(materializationContext2.Context, instance, QueryTrackingBehavior.TrackAll, equipmentEntityType0);
                }

                instance2 = instance;
            }
            else
            {
                instance2 = default(Equipment);
            }

            entry2 = (entityType2 == default(IEntityType) ? default(InternalEntityEntry) : queryContext.StartTracking(entityType2, instance2, in shadowSnapshot2));
        }
    }

    var entity0 = instance2;
    RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.IncludeReference(queryContext, entity, entity0, equipmentNavigation, default(INavigation), (GrinderProfile unnamed1, Equipment unnamed2) =>
    {
        UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_Equipment_Set(unnamed1) = unnamed2;
    }, true);
    return entity;
}, typeof(BaristaNotesContext), false, false, true), queryContext.CancellationToken);
        }

        private static object Query5_Executor;

        #endregion Query5
        #region Query6

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "vvPC3WMdcz+i+uEf/r7Pn9QPAABHcmluZGVyUHJvZmlsZVJlcG9zaXRvcnkuY3M=")]
        public static global::Microsoft.EntityFrameworkCore.Query.IIncludableQueryable<TEntity,TProperty> Query6_Include1<TEntity, TProperty>(this global::System.Linq.IQueryable<TEntity> source, global::System.Linq.Expressions.Expression<global::System.Func<TEntity,TProperty>> navigationPropertyPath)
        where TEntity : class
        {
            var precompiledQueryContext = new PrecompiledQueryContext<TEntity>(((IInfrastructure<DbContext>)source).Instance);
            return precompiledQueryContext.ToIncludable<TProperty>();
        }

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "vvPC3WMdcz+i+uEf/r7Pn/sPAABHcmluZGVyUHJvZmlsZVJlcG9zaXRvcnkuY3M=")]
        public static global::System.Threading.Tasks.Task<TSource?> Query6_FirstOrDefaultAsync2<TSource>(this global::System.Linq.IQueryable<TSource> source, global::System.Linq.Expressions.Expression<global::System.Func<TSource,global::System.Boolean>> predicate, global::System.Threading.CancellationToken cancellationToken)
        {
            var precompiledQueryContext = (PrecompiledQueryContext<TSource>)source;
            var queryContext = precompiledQueryContext.QueryContext;
            var binary1 = (BinaryExpression)predicate.Body;
            var binary2 = (BinaryExpression)binary1.Left;
            queryContext.Parameters.Add(
                "targetEquipmentId",
                Expression.Lambda<Func<object?>>(Expression.Convert(binary2.Right, typeof(object)))
                .Compile(preferInterpretation: true)
                .Invoke());
            queryContext.CancellationToken = cancellationToken;
            Query6_Executor ??= Query6_GenerateExecutor(precompiledQueryContext.DbContext, precompiledQueryContext.QueryContext);
            return ((Func<QueryContext, global::System.Threading.Tasks.Task<TSource>>)(Query6_Executor))(queryContext);
        }

        private static object Query6_GenerateExecutor(DbContext dbContext, QueryContext queryContext)
        {
            var relationalModel = dbContext.Model.GetRelationalModel();
            var relationalTypeMappingSource = dbContext.GetService<IRelationalTypeMappingSource>();
            var materializerLiftableConstantContext = new RelationalMaterializerLiftableConstantContext(
                dbContext.GetService<ShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalCommandBuilderDependencies>());
            var relationalCommandTemplate = ((IRelationalCommandTemplate)(new RelationalCommand(materializerLiftableConstantContext.CommandBuilderDependencies, "SELECT \"g\".\"Id\", \"g\".\"AnchorsJson\", \"g\".\"CreatedAt\", \"g\".\"EquipmentId\", \"g\".\"IsDeleted\", \"g\".\"LastModifiedAt\", \"g\".\"MaxSetting\", \"g\".\"MinSetting\", \"g\".\"StepSize\", \"g\".\"SyncId\", \"e\".\"Id\", \"e\".\"CreatedAt\", \"e\".\"IsActive\", \"e\".\"IsDeleted\", \"e\".\"LastModifiedAt\", \"e\".\"Name\", \"e\".\"Notes\", \"e\".\"SyncId\", \"e\".\"Type\"\nFROM \"GrinderProfiles\" AS \"g\"\nINNER JOIN \"Equipment\" AS \"e\" ON \"g\".\"EquipmentId\" = \"e\".\"Id\"\nWHERE \"g\".\"EquipmentId\" = @targetEquipmentId AND NOT (\"g\".\"IsDeleted\")\nLIMIT 1", "SELECT \"g\".\"Id\", \"g\".\"AnchorsJson\", \"g\".\"CreatedAt\", \"g\".\"EquipmentId\", \"g\".\"IsDeleted\", \"g\".\"LastModifiedAt\", \"g\".\"MaxSetting\", \"g\".\"MinSetting\", \"g\".\"StepSize\", \"g\".\"SyncId\", \"e\".\"Id\", \"e\".\"CreatedAt\", \"e\".\"IsActive\", \"e\".\"IsDeleted\", \"e\".\"LastModifiedAt\", \"e\".\"Name\", \"e\".\"Notes\", \"e\".\"SyncId\", \"e\".\"Type\"\nFROM \"GrinderProfiles\" AS \"g\"\nINNER JOIN \"Equipment\" AS \"e\" ON \"g\".\"EquipmentId\" = \"e\".\"Id\"\nWHERE \"g\".\"EquipmentId\" = @targetEquipmentId AND NOT (\"g\".\"IsDeleted\")\nLIMIT 1", new IRelationalParameter[] { new TypeMappedRelationalParameter("targetEquipmentId", "@targetEquipmentId", relationalTypeMappingSource.FindMapping(typeof(int), "INTEGER", false, false, (int? )(null), false, false, (int? )(null), (int? )(null)), false, ParameterDirection.Input) })));
            var emptyValueBuffer = ValueBuffer.Empty;
            var model = materializerLiftableConstantContext.Dependencies.Model;
            var grinderProfileEntityType = model.FindEntityType("BaristaNotes.Core.Models.GrinderProfile");
            var key = grinderProfileEntityType.FindPrimaryKey();
            var emptySnapshot = Snapshot.Empty;
            var grinderProfileEntityType0 = ((RuntimeEntityType)grinderProfileEntityType);
            var equipmentEntityType = model.FindEntityType("BaristaNotes.Core.Models.Equipment");
            var key0 = equipmentEntityType.FindPrimaryKey();
            var typeProperty = ((IPropertyBase)(((ITypeBase)equipmentEntityType).FindProperty("Type")));
            var equipmentEntityType0 = ((RuntimeEntityType)equipmentEntityType);
            var equipmentNavigation = grinderProfileEntityType.FindNavigation("Equipment");
            return Task<GrinderProfile> (QueryContext queryContext) => ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync(SingleQueryingEnumerable.Create(((RelationalQueryContext)queryContext), IRelationalCommandTemplate (Dictionary<string, object> parameters) => relationalCommandTemplate, (ReaderColumn[])(null), GrinderProfile (QueryContext queryContext, DbDataReader dataReader, ResultContext resultContext, SingleQueryResultCoordinator resultCoordinator) =>
{
    IEntityType entityType1 = default(IEntityType);
    bool hasNullKey1 = default(bool);
    IEntityType entityType2 = default(IEntityType);
    bool hasNullKey2 = default(bool);
    var materializationContext1 = new MaterializationContext(in emptyValueBuffer, queryContext.Context);
    var instance1 = default(GrinderProfile);
    var entry1 = queryContext.TryGetEntry(key, new object[] { ((object)(dataReader.GetInt32(0))) }, true, out hasNullKey1);
    if (!hasNullKey1)
    {
        if (entry1 != default(InternalEntityEntry))
        {
            entityType1 = entry1.EntityType;
            instance1 = ((GrinderProfile)(entry1.Entity));
        }
        else
        {
            var shadowSnapshot1 = emptySnapshot;
            entityType1 = grinderProfileEntityType;
            if (entityType1 == grinderProfileEntityType)
            {
                var instance = new GrinderProfile();
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_Id_Set(instance) = dataReader.GetInt32(0);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_AnchorsJson_Set(instance) = (dataReader.IsDBNull(1) ? default(string) : dataReader.GetString(1));
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_CreatedAt_Set(instance) = dataReader.GetDateTime(2);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_EquipmentId_Set(instance) = dataReader.GetInt32(3);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_IsDeleted_Set(instance) = dataReader.GetBoolean(4);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_LastModifiedAt_Set(instance) = dataReader.GetDateTime(5);
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_MaxSetting_Set(instance) = (dataReader.IsDBNull(6) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(6))));
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_MinSetting_Set(instance) = (dataReader.IsDBNull(7) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(7))));
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_StepSize_Set(instance) = (dataReader.IsDBNull(8) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(8))));
                UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_SyncId_Set(instance) = dataReader.GetGuid(9);
                if (instance is IInjectableService)
                {
                    ((IInjectableService)instance).Injected(materializationContext1.Context, instance, QueryTrackingBehavior.TrackAll, grinderProfileEntityType0);
                }

                instance1 = instance;
            }
            else
            {
                instance1 = default(GrinderProfile);
            }

            entry1 = (entityType1 == default(IEntityType) ? default(InternalEntityEntry) : queryContext.StartTracking(entityType1, instance1, in shadowSnapshot1));
        }
    }

    var entity = instance1;
    var materializationContext2 = new MaterializationContext(in emptyValueBuffer, queryContext.Context);
    var instance2 = default(Equipment);
    var entry2 = queryContext.TryGetEntry(key0, new object[] { ((object)(dataReader.GetInt32(10))) }, true, out hasNullKey2);
    if (!hasNullKey2)
    {
        if (entry2 != default(InternalEntityEntry))
        {
            entityType2 = entry2.EntityType;
            instance2 = ((Equipment)(entry2.Entity));
        }
        else
        {
            var shadowSnapshot2 = emptySnapshot;
            entityType2 = equipmentEntityType;
            if (entityType2 == equipmentEntityType)
            {
                var instance = new Equipment();
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Id_Set(instance) = dataReader.GetInt32(10);
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_CreatedAt_Set(instance) = dataReader.GetDateTime(11);
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_IsActive_Set(instance) = dataReader.GetBoolean(12);
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_IsDeleted_Set(instance) = dataReader.GetBoolean(13);
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_LastModifiedAt_Set(instance) = dataReader.GetDateTime(14);
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Name_Set(instance) = dataReader.GetString(15);
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Notes_Set(instance) = (dataReader.IsDBNull(16) ? default(string) : dataReader.GetString(16));
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_SyncId_Set(instance) = dataReader.GetGuid(17);
                UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Type_Set(instance) = ((EnumToNumberConverter<EquipmentType, int>)(((IReadOnlyProperty)typeProperty).GetTypeMapping().Converter)).ConvertFromProviderTyped(dataReader.GetInt32(18));
                if (instance is IInjectableService)
                {
                    ((IInjectableService)instance).Injected(materializationContext2.Context, instance, QueryTrackingBehavior.TrackAll, equipmentEntityType0);
                }

                instance2 = instance;
            }
            else
            {
                instance2 = default(Equipment);
            }

            entry2 = (entityType2 == default(IEntityType) ? default(InternalEntityEntry) : queryContext.StartTracking(entityType2, instance2, in shadowSnapshot2));
        }
    }

    var entity0 = instance2;
    RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.IncludeReference(queryContext, entity, entity0, equipmentNavigation, default(INavigation), (GrinderProfile unnamed1, Equipment unnamed2) =>
    {
        UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_Equipment_Set(unnamed1) = unnamed2;
    }, true);
    return entity;
}, typeof(BaristaNotesContext), false, false, true), queryContext.CancellationToken);
        }

        private static object Query6_Executor;

        #endregion Query6
        #region Unsafe accessors
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
private static extern ref int UnsafeAccessor_BaristaNotes_Core_Models_Bag_Id_Set(Bag instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BeanId>k__BackingField")]
private static extern ref int UnsafeAccessor_BaristaNotes_Core_Models_Bag_BeanId_Set(Bag instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_Bag_CreatedAt_Set(Bag instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsActive>k__BackingField")]
private static extern ref bool UnsafeAccessor_BaristaNotes_Core_Models_Bag_IsActive_Set(Bag instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsComplete>k__BackingField")]
private static extern ref bool UnsafeAccessor_BaristaNotes_Core_Models_Bag_IsComplete_Set(Bag instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsDeleted>k__BackingField")]
private static extern ref bool UnsafeAccessor_BaristaNotes_Core_Models_Bag_IsDeleted_Set(Bag instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastModifiedAt>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_Bag_LastModifiedAt_Set(Bag instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Notes>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_Bag_Notes_Set(Bag instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RoastDate>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_Bag_RoastDate_Set(Bag instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SyncId>k__BackingField")]
private static extern ref Guid UnsafeAccessor_BaristaNotes_Core_Models_Bag_SyncId_Set(Bag instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
private static extern ref int UnsafeAccessor_BaristaNotes_Core_Models_Bean_Id_Set(Bean instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_Bean_CreatedAt_Set(Bean instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsActive>k__BackingField")]
private static extern ref bool UnsafeAccessor_BaristaNotes_Core_Models_Bean_IsActive_Set(Bean instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsDeleted>k__BackingField")]
private static extern ref bool UnsafeAccessor_BaristaNotes_Core_Models_Bean_IsDeleted_Set(Bean instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastModifiedAt>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_Bean_LastModifiedAt_Set(Bean instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_Bean_Name_Set(Bean instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Notes>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_Bean_Notes_Set(Bean instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Origin>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_Bean_Origin_Set(Bean instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Roaster>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_Bean_Roaster_Set(Bean instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RoasterUrl>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_Bean_RoasterUrl_Set(Bean instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SyncId>k__BackingField")]
private static extern ref Guid UnsafeAccessor_BaristaNotes_Core_Models_Bean_SyncId_Set(Bean instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Bean>k__BackingField")]
private static extern ref Bean UnsafeAccessor_BaristaNotes_Core_Models_Bag_Bean_Set(Bag instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
private static extern ref int UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_Id_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ActualOutput>k__BackingField")]
private static extern ref decimal? UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_ActualOutput_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ActualTime>k__BackingField")]
private static extern ref decimal? UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_ActualTime_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BagId>k__BackingField")]
private static extern ref int UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_BagId_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BrewMethod>k__BackingField")]
private static extern ref BrewMethod UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_BrewMethod_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DoseIn>k__BackingField")]
private static extern ref decimal UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_DoseIn_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DrinkType>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_DrinkType_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ExpectedOutput>k__BackingField")]
private static extern ref decimal UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_ExpectedOutput_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ExpectedTime>k__BackingField")]
private static extern ref decimal UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_ExpectedTime_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<GrindMicrons>k__BackingField")]
private static extern ref int? UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_GrindMicrons_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<GrinderId>k__BackingField")]
private static extern ref int? UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_GrinderId_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsDeleted>k__BackingField")]
private static extern ref bool UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_IsDeleted_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastModifiedAt>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_LastModifiedAt_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MachineId>k__BackingField")]
private static extern ref int? UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_MachineId_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MadeById>k__BackingField")]
private static extern ref int? UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_MadeById_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MadeForId>k__BackingField")]
private static extern ref int? UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_MadeForId_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ParametersJson>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_ParametersJson_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PreinfusionTime>k__BackingField")]
private static extern ref decimal? UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_PreinfusionTime_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Rating>k__BackingField")]
private static extern ref int? UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_Rating_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SyncId>k__BackingField")]
private static extern ref Guid UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_SyncId_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TastingNotes>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_TastingNotes_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Timestamp>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_Timestamp_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<WaterTempC>k__BackingField")]
private static extern ref decimal? UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_WaterTempC_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Bag>k__BackingField")]
private static extern ref Bag UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_Bag_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
private static extern ref int UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Id_Set(Equipment instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_Equipment_CreatedAt_Set(Equipment instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsActive>k__BackingField")]
private static extern ref bool UnsafeAccessor_BaristaNotes_Core_Models_Equipment_IsActive_Set(Equipment instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsDeleted>k__BackingField")]
private static extern ref bool UnsafeAccessor_BaristaNotes_Core_Models_Equipment_IsDeleted_Set(Equipment instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastModifiedAt>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_Equipment_LastModifiedAt_Set(Equipment instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Name_Set(Equipment instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Notes>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Notes_Set(Equipment instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SyncId>k__BackingField")]
private static extern ref Guid UnsafeAccessor_BaristaNotes_Core_Models_Equipment_SyncId_Set(Equipment instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Type>k__BackingField")]
private static extern ref EquipmentType UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Type_Set(Equipment instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
private static extern ref int UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_Id_Set(GrinderProfile instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AnchorsJson>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_AnchorsJson_Set(GrinderProfile instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_CreatedAt_Set(GrinderProfile instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EquipmentId>k__BackingField")]
private static extern ref int UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_EquipmentId_Set(GrinderProfile instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsDeleted>k__BackingField")]
private static extern ref bool UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_IsDeleted_Set(GrinderProfile instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastModifiedAt>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_LastModifiedAt_Set(GrinderProfile instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MaxSetting>k__BackingField")]
private static extern ref decimal? UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_MaxSetting_Set(GrinderProfile instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MinSetting>k__BackingField")]
private static extern ref decimal? UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_MinSetting_Set(GrinderProfile instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<StepSize>k__BackingField")]
private static extern ref decimal? UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_StepSize_Set(GrinderProfile instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SyncId>k__BackingField")]
private static extern ref Guid UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_SyncId_Set(GrinderProfile instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Equipment>k__BackingField")]
private static extern ref Equipment UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_Equipment_Set(GrinderProfile instance);
        #endregion Unsafe accessors
    }
}

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data) { }
    }
}
