// <auto-generated />

using BaristaNotes.Core.Data;
using BaristaNotes.Core.Models;
using BaristaNotes.Core.Models.Enums;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Infrastructure.Internal;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.EntityFrameworkCore.Query.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

#pragma warning disable EF9100 // Precompiled query is experimental
#nullable enable annotations

namespace Microsoft.EntityFrameworkCore.GeneratedInterceptors
{
    file static class EntityFrameworkCoreInterceptors
    {
        #region Query1

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "dSGqvRzDKvWzMpEdrldv1ksEAABHcmluZFRyYW5zbGF0aW9uQ2FjaGVSZXBvc2l0b3J5LmNz")]
        public static global::System.Linq.IQueryable<TEntity> Query1_AsNoTracking1<TEntity>(this global::System.Linq.IQueryable<TEntity> source)
        where TEntity : class
        {
            var precompiledQueryContext = new PrecompiledQueryContext<TEntity>(((IInfrastructure<DbContext>)source).Instance);
            return precompiledQueryContext;
        }

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "dSGqvRzDKvWzMpEdrldv1mcEAABHcmluZFRyYW5zbGF0aW9uQ2FjaGVSZXBvc2l0b3J5LmNz")]
        public static global::System.Threading.Tasks.Task<TSource?> Query1_FirstOrDefaultAsync2<TSource>(this global::System.Linq.IQueryable<TSource> source, global::System.Linq.Expressions.Expression<global::System.Func<TSource,global::System.Boolean>> predicate, global::System.Threading.CancellationToken cancellationToken)
        {
            var precompiledQueryContext = (PrecompiledQueryContext<TSource>)source;
            var queryContext = precompiledQueryContext.QueryContext;
            var binary1 = (BinaryExpression)predicate.Body;
            var binary2 = (BinaryExpression)binary1.Left;
            var binary3 = (BinaryExpression)binary2.Left;
            var binary4 = (BinaryExpression)binary3.Left;
            queryContext.Parameters.Add(
                "targetModel",
                Expression.Lambda<Func<object?>>(Expression.Convert(binary4.Right, typeof(object)))
                .Compile(preferInterpretation: true)
                .Invoke());
            var binary6 = (BinaryExpression)binary3.Right;
            queryContext.Parameters.Add(
                "targetHint",
                Expression.Lambda<Func<object?>>(Expression.Convert(binary6.Right, typeof(object)))
                .Compile(preferInterpretation: true)
                .Invoke());
            var binary8 = (BinaryExpression)binary2.Right;
            queryContext.Parameters.Add(
                "targetMethod",
                Expression.Lambda<Func<object?>>(Expression.Convert(binary8.Right, typeof(object)))
                .Compile(preferInterpretation: true)
                .Invoke());
            var binary10 = (BinaryExpression)binary1.Right;
            queryContext.Parameters.Add(
                "now",
                Expression.Lambda<Func<object?>>(Expression.Convert(binary10.Right, typeof(object)))
                .Compile(preferInterpretation: true)
                .Invoke());
            queryContext.CancellationToken = cancellationToken;
            Query1_Executor ??= Query1_GenerateExecutor(precompiledQueryContext.DbContext, precompiledQueryContext.QueryContext);
            return ((Func<QueryContext, global::System.Threading.Tasks.Task<TSource>>)(Query1_Executor))(queryContext);
        }

        private static object Query1_GenerateExecutor(DbContext dbContext, QueryContext queryContext)
        {
            var relationalModel = dbContext.Model.GetRelationalModel();
            var relationalTypeMappingSource = dbContext.GetService<IRelationalTypeMappingSource>();
            var materializerLiftableConstantContext = new RelationalMaterializerLiftableConstantContext(
                dbContext.GetService<ShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalCommandBuilderDependencies>());
            var commandBuilderDependencies = materializerLiftableConstantContext.CommandBuilderDependencies;
            var relationalCommandTemplate = ((IRelationalCommandTemplate)(new RelationalCommand(commandBuilderDependencies, "SELECT \"g\".\"Id\", \"g\".\"BrewMethod\", \"g\".\"Confidence\", \"g\".\"CreatedAt\", \"g\".\"ExpiresAt\", \"g\".\"Explanation\", \"g\".\"GrindHintNormalized\", \"g\".\"GrinderModelNormalized\", \"g\".\"MaxSetting\", \"g\".\"MinSetting\", \"g\".\"Source\", \"g\".\"SuggestedSetting\"\nFROM \"GrindTranslationCache\" AS \"g\"\nWHERE 0\nLIMIT 1", "SELECT \"g\".\"Id\", \"g\".\"BrewMethod\", \"g\".\"Confidence\", \"g\".\"CreatedAt\", \"g\".\"ExpiresAt\", \"g\".\"Explanation\", \"g\".\"GrindHintNormalized\", \"g\".\"GrinderModelNormalized\", \"g\".\"MaxSetting\", \"g\".\"MinSetting\", \"g\".\"Source\", \"g\".\"SuggestedSetting\"\nFROM \"GrindTranslationCache\" AS \"g\"\nWHERE 0\nLIMIT 1", new IRelationalParameter[] { })));
            var findMapping = relationalTypeMappingSource.FindMapping(typeof(string), "TEXT", false, false, (int? )(null), false, false, (int? )(null), (int? )(null));
            var relationalCommandTemplate0 = ((IRelationalCommandTemplate)(new RelationalCommand(commandBuilderDependencies, "SELECT \"g\".\"Id\", \"g\".\"BrewMethod\", \"g\".\"Confidence\", \"g\".\"CreatedAt\", \"g\".\"ExpiresAt\", \"g\".\"Explanation\", \"g\".\"GrindHintNormalized\", \"g\".\"GrinderModelNormalized\", \"g\".\"MaxSetting\", \"g\".\"MinSetting\", \"g\".\"Source\", \"g\".\"SuggestedSetting\"\nFROM \"GrindTranslationCache\" AS \"g\"\nWHERE \"g\".\"GrinderModelNormalized\" = @targetModel AND \"g\".\"GrindHintNormalized\" = @targetHint AND \"g\".\"BrewMethod\" = @targetMethod AND \"g\".\"ExpiresAt\" > @now\nLIMIT 1", "SELECT \"g\".\"Id\", \"g\".\"BrewMethod\", \"g\".\"Confidence\", \"g\".\"CreatedAt\", \"g\".\"ExpiresAt\", \"g\".\"Explanation\", \"g\".\"GrindHintNormalized\", \"g\".\"GrinderModelNormalized\", \"g\".\"MaxSetting\", \"g\".\"MinSetting\", \"g\".\"Source\", \"g\".\"SuggestedSetting\"\nFROM \"GrindTranslationCache\" AS \"g\"\nWHERE \"g\".\"GrinderModelNormalized\" = @targetModel AND \"g\".\"GrindHintNormalized\" = @targetHint AND \"g\".\"BrewMethod\" = @targetMethod AND \"g\".\"ExpiresAt\" > @now\nLIMIT 1", new IRelationalParameter[] { new TypeMappedRelationalParameter("targetModel", "@targetModel", findMapping, true, ParameterDirection.Input), new TypeMappedRelationalParameter("targetHint", "@targetHint", findMapping, true, ParameterDirection.Input), new TypeMappedRelationalParameter("targetMethod", "@targetMethod", relationalTypeMappingSource.FindMapping(typeof(BrewMethod), "INTEGER", false, false, (int? )(null), false, false, (int? )(null), (int? )(null)), false, ParameterDirection.Input), new TypeMappedRelationalParameter("now", "@now", relationalTypeMappingSource.FindMapping(typeof(DateTime), "TEXT", false, false, (int? )(null), false, false, (int? )(null), (int? )(null)), false, ParameterDirection.Input) })));
            var emptyValueBuffer = ValueBuffer.Empty;
            var emptySnapshot = Snapshot.Empty;
            var grindTranslationCacheEntityType = materializerLiftableConstantContext.Dependencies.Model.FindEntityType("BaristaNotes.Core.Models.GrindTranslationCache");
            var brewMethodProperty = ((IPropertyBase)(((ITypeBase)grindTranslationCacheEntityType).FindProperty("BrewMethod")));
            var grindTranslationCacheEntityType0 = ((RuntimeEntityType)grindTranslationCacheEntityType);
            var unknown = grindTranslationCacheEntityType.FindPrimaryKey().Properties;
            return Task<GrindTranslationCache> (QueryContext queryContext) => ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync(SingleQueryingEnumerable.Create(((RelationalQueryContext)queryContext), IRelationalCommandTemplate (Dictionary<string, object> parameters) =>
{
    IRelationalCommandTemplate result = default(IRelationalCommandTemplate);
    if (parameters["targetModel"] == null)
    {
        if (parameters["targetHint"] == null)
        {
            result = relationalCommandTemplate;
        }
        else
        {
            result = relationalCommandTemplate;
        }
    }
    else
    {
        if (parameters["targetHint"] == null)
        {
            result = relationalCommandTemplate;
        }
        else
        {
            result = relationalCommandTemplate0;
        }
    }

    return result;
}, (ReaderColumn[])(null), GrindTranslationCache (QueryContext queryContext, DbDataReader dataReader, ResultContext resultContext, SingleQueryResultCoordinator resultCoordinator) =>
{
    IEntityType entityType1 = default(IEntityType);
    var materializationContext1 = new MaterializationContext(in emptyValueBuffer, queryContext.Context);
    var instance1 = default(GrindTranslationCache);
    if (((object)(dataReader.GetInt32(0))) != null)
    {
        var shadowSnapshot1 = emptySnapshot;
        entityType1 = grindTranslationCacheEntityType;
        if (entityType1 == grindTranslationCacheEntityType)
        {
            var instance = new GrindTranslationCache();
            UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_Id_Set(instance) = dataReader.GetInt32(0);
            UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_BrewMethod_Set(instance) = ((EnumToNumberConverter<BrewMethod, int>)(((IReadOnlyProperty)brewMethodProperty).GetTypeMapping().Converter)).ConvertFromProviderTyped(dataReader.GetInt32(1));
            UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_Confidence_Set(instance) = dataReader.GetString(2);
            UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_CreatedAt_Set(instance) = dataReader.GetDateTime(3);
            UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_ExpiresAt_Set(instance) = dataReader.GetDateTime(4);
            UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_Explanation_Set(instance) = (dataReader.IsDBNull(5) ? default(string) : dataReader.GetString(5));
            UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_GrindHintNormalized_Set(instance) = dataReader.GetString(6);
            UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_GrinderModelNormalized_Set(instance) = dataReader.GetString(7);
            UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_MaxSetting_Set(instance) = (dataReader.IsDBNull(8) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(8))));
            UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_MinSetting_Set(instance) = (dataReader.IsDBNull(9) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(9))));
            UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_Source_Set(instance) = dataReader.GetString(10);
            UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_SuggestedSetting_Set(instance) = (dataReader.IsDBNull(11) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(11))));
            if (instance is IInjectableService)
            {
                ((IInjectableService)instance).Injected(materializationContext1.Context, instance, QueryTrackingBehavior.NoTracking, grindTranslationCacheEntityType0);
            }

            instance1 = instance;
        }
        else
        {
            instance1 = default(GrindTranslationCache);
        }
    }
    else
    {
        var keyValues1 = new object[]
        {
            ((object)(dataReader.GetInt32(0)))
        };
        ShapedQueryCompilingExpressionVisitor.CreateNullKeyValueInNoTrackingQuery(grindTranslationCacheEntityType, unknown, keyValues1);
    }

    var entity = instance1;
    return entity;
}, typeof(BaristaNotesContext), false, false, true), queryContext.CancellationToken);
        }

        private static object Query1_Executor;

        #endregion Query1
        #region Query2

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "dSGqvRzDKvWzMpEdrldv1mcGAABHcmluZFRyYW5zbGF0aW9uQ2FjaGVSZXBvc2l0b3J5LmNz")]
        public static global::System.Threading.Tasks.Task<TSource?> Query2_FirstOrDefaultAsync1<TSource>(this global::System.Linq.IQueryable<TSource> source, global::System.Linq.Expressions.Expression<global::System.Func<TSource,global::System.Boolean>> predicate, global::System.Threading.CancellationToken cancellationToken)
        {
            var precompiledQueryContext = new PrecompiledQueryContext<TSource>(((IInfrastructure<DbContext>)source).Instance);
            var queryContext = precompiledQueryContext.QueryContext;
            var binary1 = (BinaryExpression)predicate.Body;
            var binary2 = (BinaryExpression)binary1.Left;
            var binary3 = (BinaryExpression)binary2.Left;
            queryContext.Parameters.Add(
                "targetModel",
                Expression.Lambda<Func<object?>>(Expression.Convert(binary3.Right, typeof(object)))
                .Compile(preferInterpretation: true)
                .Invoke());
            var binary5 = (BinaryExpression)binary2.Right;
            queryContext.Parameters.Add(
                "targetHint",
                Expression.Lambda<Func<object?>>(Expression.Convert(binary5.Right, typeof(object)))
                .Compile(preferInterpretation: true)
                .Invoke());
            var binary7 = (BinaryExpression)binary1.Right;
            queryContext.Parameters.Add(
                "targetMethod",
                Expression.Lambda<Func<object?>>(Expression.Convert(binary7.Right, typeof(object)))
                .Compile(preferInterpretation: true)
                .Invoke());
            queryContext.CancellationToken = cancellationToken;
            Query2_Executor ??= Query2_GenerateExecutor(precompiledQueryContext.DbContext, precompiledQueryContext.QueryContext);
            return ((Func<QueryContext, global::System.Threading.Tasks.Task<TSource>>)(Query2_Executor))(queryContext);
        }

        private static object Query2_GenerateExecutor(DbContext dbContext, QueryContext queryContext)
        {
            var relationalModel = dbContext.Model.GetRelationalModel();
            var relationalTypeMappingSource = dbContext.GetService<IRelationalTypeMappingSource>();
            var materializerLiftableConstantContext = new RelationalMaterializerLiftableConstantContext(
                dbContext.GetService<ShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalCommandBuilderDependencies>());
            var commandBuilderDependencies = materializerLiftableConstantContext.CommandBuilderDependencies;
            var relationalCommandTemplate = ((IRelationalCommandTemplate)(new RelationalCommand(commandBuilderDependencies, "SELECT \"g\".\"Id\", \"g\".\"BrewMethod\", \"g\".\"Confidence\", \"g\".\"CreatedAt\", \"g\".\"ExpiresAt\", \"g\".\"Explanation\", \"g\".\"GrindHintNormalized\", \"g\".\"GrinderModelNormalized\", \"g\".\"MaxSetting\", \"g\".\"MinSetting\", \"g\".\"Source\", \"g\".\"SuggestedSetting\"\nFROM \"GrindTranslationCache\" AS \"g\"\nWHERE 0\nLIMIT 1", "SELECT \"g\".\"Id\", \"g\".\"BrewMethod\", \"g\".\"Confidence\", \"g\".\"CreatedAt\", \"g\".\"ExpiresAt\", \"g\".\"Explanation\", \"g\".\"GrindHintNormalized\", \"g\".\"GrinderModelNormalized\", \"g\".\"MaxSetting\", \"g\".\"MinSetting\", \"g\".\"Source\", \"g\".\"SuggestedSetting\"\nFROM \"GrindTranslationCache\" AS \"g\"\nWHERE 0\nLIMIT 1", new IRelationalParameter[] { })));
            var findMapping = relationalTypeMappingSource.FindMapping(typeof(string), "TEXT", false, false, (int? )(null), false, false, (int? )(null), (int? )(null));
            var relationalCommandTemplate0 = ((IRelationalCommandTemplate)(new RelationalCommand(commandBuilderDependencies, "SELECT \"g\".\"Id\", \"g\".\"BrewMethod\", \"g\".\"Confidence\", \"g\".\"CreatedAt\", \"g\".\"ExpiresAt\", \"g\".\"Explanation\", \"g\".\"GrindHintNormalized\", \"g\".\"GrinderModelNormalized\", \"g\".\"MaxSetting\", \"g\".\"MinSetting\", \"g\".\"Source\", \"g\".\"SuggestedSetting\"\nFROM \"GrindTranslationCache\" AS \"g\"\nWHERE \"g\".\"GrinderModelNormalized\" = @targetModel AND \"g\".\"GrindHintNormalized\" = @targetHint AND \"g\".\"BrewMethod\" = @targetMethod\nLIMIT 1", "SELECT \"g\".\"Id\", \"g\".\"BrewMethod\", \"g\".\"Confidence\", \"g\".\"CreatedAt\", \"g\".\"ExpiresAt\", \"g\".\"Explanation\", \"g\".\"GrindHintNormalized\", \"g\".\"GrinderModelNormalized\", \"g\".\"MaxSetting\", \"g\".\"MinSetting\", \"g\".\"Source\", \"g\".\"SuggestedSetting\"\nFROM \"GrindTranslationCache\" AS \"g\"\nWHERE \"g\".\"GrinderModelNormalized\" = @targetModel AND \"g\".\"GrindHintNormalized\" = @targetHint AND \"g\".\"BrewMethod\" = @targetMethod\nLIMIT 1", new IRelationalParameter[] { new TypeMappedRelationalParameter("targetModel", "@targetModel", findMapping, true, ParameterDirection.Input), new TypeMappedRelationalParameter("targetHint", "@targetHint", findMapping, true, ParameterDirection.Input), new TypeMappedRelationalParameter("targetMethod", "@targetMethod", relationalTypeMappingSource.FindMapping(typeof(BrewMethod), "INTEGER", false, false, (int? )(null), false, false, (int? )(null), (int? )(null)), false, ParameterDirection.Input) })));
            var emptyValueBuffer = ValueBuffer.Empty;
            var grindTranslationCacheEntityType = materializerLiftableConstantContext.Dependencies.Model.FindEntityType("BaristaNotes.Core.Models.GrindTranslationCache");
            var key = grindTranslationCacheEntityType.FindPrimaryKey();
            var emptySnapshot = Snapshot.Empty;
            var brewMethodProperty = ((IPropertyBase)(((ITypeBase)grindTranslationCacheEntityType).FindProperty("BrewMethod")));
            var grindTranslationCacheEntityType0 = ((RuntimeEntityType)grindTranslationCacheEntityType);
            return Task<GrindTranslationCache> (QueryContext queryContext) => ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync(SingleQueryingEnumerable.Create(((RelationalQueryContext)queryContext), IRelationalCommandTemplate (Dictionary<string, object> parameters) =>
{
    IRelationalCommandTemplate result = default(IRelationalCommandTemplate);
    if (parameters["targetModel"] == null)
    {
        if (parameters["targetHint"] == null)
        {
            result = relationalCommandTemplate;
        }
        else
        {
            result = relationalCommandTemplate;
        }
    }
    else
    {
        if (parameters["targetHint"] == null)
        {
            result = relationalCommandTemplate;
        }
        else
        {
            result = relationalCommandTemplate0;
        }
    }

    return result;
}, (ReaderColumn[])(null), GrindTranslationCache (QueryContext queryContext, DbDataReader dataReader, ResultContext resultContext, SingleQueryResultCoordinator resultCoordinator) =>
{
    IEntityType entityType1 = default(IEntityType);
    bool hasNullKey1 = default(bool);
    var materializationContext1 = new MaterializationContext(in emptyValueBuffer, queryContext.Context);
    var instance1 = default(GrindTranslationCache);
    var entry1 = queryContext.TryGetEntry(key, new object[] { ((object)(dataReader.GetInt32(0))) }, true, out hasNullKey1);
    if (!hasNullKey1)
    {
        if (entry1 != default(InternalEntityEntry))
        {
            entityType1 = entry1.EntityType;
            instance1 = ((GrindTranslationCache)(entry1.Entity));
        }
        else
        {
            var shadowSnapshot1 = emptySnapshot;
            entityType1 = grindTranslationCacheEntityType;
            if (entityType1 == grindTranslationCacheEntityType)
            {
                var instance = new GrindTranslationCache();
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_Id_Set(instance) = dataReader.GetInt32(0);
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_BrewMethod_Set(instance) = ((EnumToNumberConverter<BrewMethod, int>)(((IReadOnlyProperty)brewMethodProperty).GetTypeMapping().Converter)).ConvertFromProviderTyped(dataReader.GetInt32(1));
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_Confidence_Set(instance) = dataReader.GetString(2);
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_CreatedAt_Set(instance) = dataReader.GetDateTime(3);
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_ExpiresAt_Set(instance) = dataReader.GetDateTime(4);
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_Explanation_Set(instance) = (dataReader.IsDBNull(5) ? default(string) : dataReader.GetString(5));
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_GrindHintNormalized_Set(instance) = dataReader.GetString(6);
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_GrinderModelNormalized_Set(instance) = dataReader.GetString(7);
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_MaxSetting_Set(instance) = (dataReader.IsDBNull(8) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(8))));
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_MinSetting_Set(instance) = (dataReader.IsDBNull(9) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(9))));
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_Source_Set(instance) = dataReader.GetString(10);
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_SuggestedSetting_Set(instance) = (dataReader.IsDBNull(11) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(11))));
                if (instance is IInjectableService)
                {
                    ((IInjectableService)instance).Injected(materializationContext1.Context, instance, QueryTrackingBehavior.TrackAll, grindTranslationCacheEntityType0);
                }

                instance1 = instance;
            }
            else
            {
                instance1 = default(GrindTranslationCache);
            }

            entry1 = (entityType1 == default(IEntityType) ? default(InternalEntityEntry) : queryContext.StartTracking(entityType1, instance1, in shadowSnapshot1));
        }
    }

    var entity = instance1;
    return entity;
}, typeof(BaristaNotesContext), false, false, true), queryContext.CancellationToken);
        }

        private static object Query2_Executor;

        #endregion Query2
        #region Query3

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "dSGqvRzDKvWzMpEdrldv1iMKAABHcmluZFRyYW5zbGF0aW9uQ2FjaGVSZXBvc2l0b3J5LmNz")]
        public static global::System.Linq.IQueryable<TSource> Query3_Where1<TSource>(this global::System.Linq.IQueryable<TSource> source, global::System.Linq.Expressions.Expression<global::System.Func<TSource,global::System.Boolean>> predicate)
        {
            var precompiledQueryContext = new PrecompiledQueryContext<TSource>(((IInfrastructure<DbContext>)source).Instance);
            var queryContext = precompiledQueryContext.QueryContext;
            var binary1 = (BinaryExpression)predicate.Body;
            queryContext.Parameters.Add(
                "cutoff",
                Expression.Lambda<Func<object?>>(Expression.Convert(binary1.Right, typeof(object)))
                .Compile(preferInterpretation: true)
                .Invoke());
            return precompiledQueryContext;
        }

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "dSGqvRzDKvWzMpEdrldv1lIKAABHcmluZFRyYW5zbGF0aW9uQ2FjaGVSZXBvc2l0b3J5LmNz")]
        public static global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<TSource>> Query3_ToListAsync2<TSource>(this global::System.Linq.IQueryable<TSource> source, global::System.Threading.CancellationToken cancellationToken)
        {
            var precompiledQueryContext = (PrecompiledQueryContext<TSource>)source;
            var queryContext = precompiledQueryContext.QueryContext;
            queryContext.CancellationToken = cancellationToken;
            Query3_Executor ??= Query3_GenerateExecutor(precompiledQueryContext.DbContext, precompiledQueryContext.QueryContext);
            var queryingEnumerable = ((Func<QueryContext, IAsyncEnumerable<TSource>>)(Query3_Executor))(queryContext);
            var asyncQueryingEnumerable = new PrecompiledQueryableAsyncEnumerableAdapter<TSource>(queryingEnumerable);
            return asyncQueryingEnumerable.ToListAsync(cancellationToken);
        }

        private static object Query3_GenerateExecutor(DbContext dbContext, QueryContext queryContext)
        {
            var relationalModel = dbContext.Model.GetRelationalModel();
            var relationalTypeMappingSource = dbContext.GetService<IRelationalTypeMappingSource>();
            var materializerLiftableConstantContext = new RelationalMaterializerLiftableConstantContext(
                dbContext.GetService<ShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalCommandBuilderDependencies>());
            var relationalCommandTemplate = ((IRelationalCommandTemplate)(new RelationalCommand(materializerLiftableConstantContext.CommandBuilderDependencies, "SELECT \"g\".\"Id\", \"g\".\"BrewMethod\", \"g\".\"Confidence\", \"g\".\"CreatedAt\", \"g\".\"ExpiresAt\", \"g\".\"Explanation\", \"g\".\"GrindHintNormalized\", \"g\".\"GrinderModelNormalized\", \"g\".\"MaxSetting\", \"g\".\"MinSetting\", \"g\".\"Source\", \"g\".\"SuggestedSetting\"\nFROM \"GrindTranslationCache\" AS \"g\"\nWHERE \"g\".\"ExpiresAt\" <= @cutoff", "SELECT \"g\".\"Id\", \"g\".\"BrewMethod\", \"g\".\"Confidence\", \"g\".\"CreatedAt\", \"g\".\"ExpiresAt\", \"g\".\"Explanation\", \"g\".\"GrindHintNormalized\", \"g\".\"GrinderModelNormalized\", \"g\".\"MaxSetting\", \"g\".\"MinSetting\", \"g\".\"Source\", \"g\".\"SuggestedSetting\"\nFROM \"GrindTranslationCache\" AS \"g\"\nWHERE \"g\".\"ExpiresAt\" <= @cutoff", new IRelationalParameter[] { new TypeMappedRelationalParameter("cutoff", "@cutoff", relationalTypeMappingSource.FindMapping(typeof(DateTime), "TEXT", false, false, (int? )(null), false, false, (int? )(null), (int? )(null)), false, ParameterDirection.Input) })));
            var emptyValueBuffer = ValueBuffer.Empty;
            var grindTranslationCacheEntityType = materializerLiftableConstantContext.Dependencies.Model.FindEntityType("BaristaNotes.Core.Models.GrindTranslationCache");
            var key = grindTranslationCacheEntityType.FindPrimaryKey();
            var emptySnapshot = Snapshot.Empty;
            var brewMethodProperty = ((IPropertyBase)(((ITypeBase)grindTranslationCacheEntityType).FindProperty("BrewMethod")));
            var grindTranslationCacheEntityType0 = ((RuntimeEntityType)grindTranslationCacheEntityType);
            return IAsyncEnumerable<GrindTranslationCache> (QueryContext queryContext) => SingleQueryingEnumerable.Create(((RelationalQueryContext)queryContext), IRelationalCommandTemplate (Dictionary<string, object> parameters) => relationalCommandTemplate, (ReaderColumn[])(null), GrindTranslationCache (QueryContext queryContext, DbDataReader dataReader, ResultContext resultContext, SingleQueryResultCoordinator resultCoordinator) =>
{
    IEntityType entityType1 = default(IEntityType);
    bool hasNullKey1 = default(bool);
    var materializationContext1 = new MaterializationContext(in emptyValueBuffer, queryContext.Context);
    var instance1 = default(GrindTranslationCache);
    var entry1 = queryContext.TryGetEntry(key, new object[] { ((object)(dataReader.GetInt32(0))) }, true, out hasNullKey1);
    if (!hasNullKey1)
    {
        if (entry1 != default(InternalEntityEntry))
        {
            entityType1 = entry1.EntityType;
            instance1 = ((GrindTranslationCache)(entry1.Entity));
        }
        else
        {
            var shadowSnapshot1 = emptySnapshot;
            entityType1 = grindTranslationCacheEntityType;
            if (entityType1 == grindTranslationCacheEntityType)
            {
                var instance = new GrindTranslationCache();
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_Id_Set(instance) = dataReader.GetInt32(0);
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_BrewMethod_Set(instance) = ((EnumToNumberConverter<BrewMethod, int>)(((IReadOnlyProperty)brewMethodProperty).GetTypeMapping().Converter)).ConvertFromProviderTyped(dataReader.GetInt32(1));
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_Confidence_Set(instance) = dataReader.GetString(2);
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_CreatedAt_Set(instance) = dataReader.GetDateTime(3);
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_ExpiresAt_Set(instance) = dataReader.GetDateTime(4);
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_Explanation_Set(instance) = (dataReader.IsDBNull(5) ? default(string) : dataReader.GetString(5));
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_GrindHintNormalized_Set(instance) = dataReader.GetString(6);
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_GrinderModelNormalized_Set(instance) = dataReader.GetString(7);
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_MaxSetting_Set(instance) = (dataReader.IsDBNull(8) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(8))));
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_MinSetting_Set(instance) = (dataReader.IsDBNull(9) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(9))));
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_Source_Set(instance) = dataReader.GetString(10);
                UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_SuggestedSetting_Set(instance) = (dataReader.IsDBNull(11) ? default(decimal? ) : ((decimal? )(dataReader.GetDecimal(11))));
                if (instance is IInjectableService)
                {
                    ((IInjectableService)instance).Injected(materializationContext1.Context, instance, QueryTrackingBehavior.TrackAll, grindTranslationCacheEntityType0);
                }

                instance1 = instance;
            }
            else
            {
                instance1 = default(GrindTranslationCache);
            }

            entry1 = (entityType1 == default(IEntityType) ? default(InternalEntityEntry) : queryContext.StartTracking(entityType1, instance1, in shadowSnapshot1));
        }
    }

    var entity = instance1;
    return entity;
}, typeof(BaristaNotesContext), false, false, true);
        }

        private static object Query3_Executor;

        #endregion Query3
        #region Unsafe accessors
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
private static extern ref int UnsafeAccessor_BaristaNotes_Core_Models_Bag_Id_Set(Bag instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BeanId>k__BackingField")]
private static extern ref int UnsafeAccessor_BaristaNotes_Core_Models_Bag_BeanId_Set(Bag instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_Bag_CreatedAt_Set(Bag instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsActive>k__BackingField")]
private static extern ref bool UnsafeAccessor_BaristaNotes_Core_Models_Bag_IsActive_Set(Bag instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsComplete>k__BackingField")]
private static extern ref bool UnsafeAccessor_BaristaNotes_Core_Models_Bag_IsComplete_Set(Bag instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsDeleted>k__BackingField")]
private static extern ref bool UnsafeAccessor_BaristaNotes_Core_Models_Bag_IsDeleted_Set(Bag instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastModifiedAt>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_Bag_LastModifiedAt_Set(Bag instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Notes>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_Bag_Notes_Set(Bag instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RoastDate>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_Bag_RoastDate_Set(Bag instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SyncId>k__BackingField")]
private static extern ref Guid UnsafeAccessor_BaristaNotes_Core_Models_Bag_SyncId_Set(Bag instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
private static extern ref int UnsafeAccessor_BaristaNotes_Core_Models_Bean_Id_Set(Bean instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_Bean_CreatedAt_Set(Bean instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsActive>k__BackingField")]
private static extern ref bool UnsafeAccessor_BaristaNotes_Core_Models_Bean_IsActive_Set(Bean instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsDeleted>k__BackingField")]
private static extern ref bool UnsafeAccessor_BaristaNotes_Core_Models_Bean_IsDeleted_Set(Bean instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastModifiedAt>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_Bean_LastModifiedAt_Set(Bean instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_Bean_Name_Set(Bean instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Notes>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_Bean_Notes_Set(Bean instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Origin>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_Bean_Origin_Set(Bean instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Roaster>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_Bean_Roaster_Set(Bean instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RoasterUrl>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_Bean_RoasterUrl_Set(Bean instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SyncId>k__BackingField")]
private static extern ref Guid UnsafeAccessor_BaristaNotes_Core_Models_Bean_SyncId_Set(Bean instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Bean>k__BackingField")]
private static extern ref Bean UnsafeAccessor_BaristaNotes_Core_Models_Bag_Bean_Set(Bag instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
private static extern ref int UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_Id_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ActualOutput>k__BackingField")]
private static extern ref decimal? UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_ActualOutput_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ActualTime>k__BackingField")]
private static extern ref decimal? UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_ActualTime_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BagId>k__BackingField")]
private static extern ref int UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_BagId_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BrewMethod>k__BackingField")]
private static extern ref BrewMethod UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_BrewMethod_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DoseIn>k__BackingField")]
private static extern ref decimal UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_DoseIn_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DrinkType>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_DrinkType_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ExpectedOutput>k__BackingField")]
private static extern ref decimal UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_ExpectedOutput_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ExpectedTime>k__BackingField")]
private static extern ref decimal UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_ExpectedTime_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<GrindMicrons>k__BackingField")]
private static extern ref int? UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_GrindMicrons_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<GrinderId>k__BackingField")]
private static extern ref int? UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_GrinderId_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsDeleted>k__BackingField")]
private static extern ref bool UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_IsDeleted_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastModifiedAt>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_LastModifiedAt_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MachineId>k__BackingField")]
private static extern ref int? UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_MachineId_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MadeById>k__BackingField")]
private static extern ref int? UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_MadeById_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MadeForId>k__BackingField")]
private static extern ref int? UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_MadeForId_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ParametersJson>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_ParametersJson_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PreinfusionTime>k__BackingField")]
private static extern ref decimal? UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_PreinfusionTime_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Rating>k__BackingField")]
private static extern ref int? UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_Rating_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SyncId>k__BackingField")]
private static extern ref Guid UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_SyncId_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TastingNotes>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_TastingNotes_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Timestamp>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_Timestamp_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<WaterTempC>k__BackingField")]
private static extern ref decimal? UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_WaterTempC_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Bag>k__BackingField")]
private static extern ref Bag UnsafeAccessor_BaristaNotes_Core_Models_ShotRecord_Bag_Set(ShotRecord instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
private static extern ref int UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Id_Set(Equipment instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_Equipment_CreatedAt_Set(Equipment instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsActive>k__BackingField")]
private static extern ref bool UnsafeAccessor_BaristaNotes_Core_Models_Equipment_IsActive_Set(Equipment instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsDeleted>k__BackingField")]
private static extern ref bool UnsafeAccessor_BaristaNotes_Core_Models_Equipment_IsDeleted_Set(Equipment instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastModifiedAt>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_Equipment_LastModifiedAt_Set(Equipment instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Name_Set(Equipment instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Notes>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Notes_Set(Equipment instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SyncId>k__BackingField")]
private static extern ref Guid UnsafeAccessor_BaristaNotes_Core_Models_Equipment_SyncId_Set(Equipment instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Type>k__BackingField")]
private static extern ref EquipmentType UnsafeAccessor_BaristaNotes_Core_Models_Equipment_Type_Set(Equipment instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
private static extern ref int UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_Id_Set(GrinderProfile instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AnchorsJson>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_AnchorsJson_Set(GrinderProfile instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_CreatedAt_Set(GrinderProfile instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EquipmentId>k__BackingField")]
private static extern ref int UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_EquipmentId_Set(GrinderProfile instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsDeleted>k__BackingField")]
private static extern ref bool UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_IsDeleted_Set(GrinderProfile instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastModifiedAt>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_LastModifiedAt_Set(GrinderProfile instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MaxSetting>k__BackingField")]
private static extern ref decimal? UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_MaxSetting_Set(GrinderProfile instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MinSetting>k__BackingField")]
private static extern ref decimal? UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_MinSetting_Set(GrinderProfile instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<StepSize>k__BackingField")]
private static extern ref decimal? UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_StepSize_Set(GrinderProfile instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SyncId>k__BackingField")]
private static extern ref Guid UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_SyncId_Set(GrinderProfile instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Equipment>k__BackingField")]
private static extern ref Equipment UnsafeAccessor_BaristaNotes_Core_Models_GrinderProfile_Equipment_Set(GrinderProfile instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
private static extern ref int UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_Id_Set(GrindTranslationCache instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BrewMethod>k__BackingField")]
private static extern ref BrewMethod UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_BrewMethod_Set(GrindTranslationCache instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Confidence>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_Confidence_Set(GrindTranslationCache instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_CreatedAt_Set(GrindTranslationCache instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ExpiresAt>k__BackingField")]
private static extern ref DateTime UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_ExpiresAt_Set(GrindTranslationCache instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Explanation>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_Explanation_Set(GrindTranslationCache instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<GrindHintNormalized>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_GrindHintNormalized_Set(GrindTranslationCache instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<GrinderModelNormalized>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_GrinderModelNormalized_Set(GrindTranslationCache instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MaxSetting>k__BackingField")]
private static extern ref decimal? UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_MaxSetting_Set(GrindTranslationCache instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MinSetting>k__BackingField")]
private static extern ref decimal? UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_MinSetting_Set(GrindTranslationCache instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Source>k__BackingField")]
private static extern ref string UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_Source_Set(GrindTranslationCache instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SuggestedSetting>k__BackingField")]
private static extern ref decimal? UnsafeAccessor_BaristaNotes_Core_Models_GrindTranslationCache_SuggestedSetting_Set(GrindTranslationCache instance);
        #endregion Unsafe accessors
    }
}

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data) { }
    }
}
