// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using BaristaNotes.Core.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BaristaNotes.Core.Data.CompiledModels
{
    public static class GrinderProfileUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(GrinderProfile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AnchorsJson>k__BackingField")]
        public static extern ref string AnchorsJson(GrinderProfile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTime CreatedAt(GrinderProfile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EquipmentId>k__BackingField")]
        public static extern ref int EquipmentId(GrinderProfile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsDeleted>k__BackingField")]
        public static extern ref bool IsDeleted(GrinderProfile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastModifiedAt>k__BackingField")]
        public static extern ref DateTime LastModifiedAt(GrinderProfile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MaxSetting>k__BackingField")]
        public static extern ref decimal? MaxSetting(GrinderProfile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MinSetting>k__BackingField")]
        public static extern ref decimal? MinSetting(GrinderProfile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<StepSize>k__BackingField")]
        public static extern ref decimal? StepSize(GrinderProfile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SyncId>k__BackingField")]
        public static extern ref Guid SyncId(GrinderProfile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Equipment>k__BackingField")]
        public static extern ref Equipment Equipment(GrinderProfile @this);
    }
}
