// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using BaristaNotes.Core.Models;
using BaristaNotes.Core.Models.Enums;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BaristaNotes.Core.Data.CompiledModels;

public static class GrindTranslationCacheUnsafeAccessors
{
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
    public static extern ref int Id(GrindTranslationCache @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BrewMethod>k__BackingField")]
    public static extern ref BrewMethod BrewMethod(GrindTranslationCache @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Confidence>k__BackingField")]
    public static extern ref string Confidence(GrindTranslationCache @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
    public static extern ref DateTime CreatedAt(GrindTranslationCache @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ExpiresAt>k__BackingField")]
    public static extern ref DateTime ExpiresAt(GrindTranslationCache @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Explanation>k__BackingField")]
    public static extern ref string Explanation(GrindTranslationCache @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<GrindHintNormalized>k__BackingField")]
    public static extern ref string GrindHintNormalized(GrindTranslationCache @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<GrinderModelNormalized>k__BackingField")]
    public static extern ref string GrinderModelNormalized(GrindTranslationCache @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MaxSetting>k__BackingField")]
    public static extern ref decimal? MaxSetting(GrindTranslationCache @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MinSetting>k__BackingField")]
    public static extern ref decimal? MinSetting(GrindTranslationCache @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Source>k__BackingField")]
    public static extern ref string Source(GrindTranslationCache @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SuggestedSetting>k__BackingField")]
    public static extern ref decimal? SuggestedSetting(GrindTranslationCache @this);
}
