// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using BaristaNotes.Core.Models;
using BaristaNotes.Core.Models.Enums;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BaristaNotes.Core.Data.CompiledModels
{
    public static class RecipeUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(Recipe @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BeanId>k__BackingField")]
        public static extern ref int BeanId(Recipe @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BrewMethod>k__BackingField")]
        public static extern ref BrewMethod BrewMethod(Recipe @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BrewTempC>k__BackingField")]
        public static extern ref decimal? BrewTempC(Recipe @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DoseIn>k__BackingField")]
        public static extern ref decimal? DoseIn(Recipe @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FetchedAt>k__BackingField")]
        public static extern ref DateTime FetchedAt(Recipe @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<GrindHint>k__BackingField")]
        public static extern ref string GrindHint(Recipe @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsDeleted>k__BackingField")]
        public static extern ref bool IsDeleted(Recipe @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsEditedByUser>k__BackingField")]
        public static extern ref bool IsEditedByUser(Recipe @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastModifiedAt>k__BackingField")]
        public static extern ref DateTime LastModifiedAt(Recipe @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Notes>k__BackingField")]
        public static extern ref string Notes(Recipe @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OutputAmount>k__BackingField")]
        public static extern ref decimal? OutputAmount(Recipe @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ParametersJson>k__BackingField")]
        public static extern ref string ParametersJson(Recipe @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Source>k__BackingField")]
        public static extern ref RecipeSource Source(Recipe @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SourceUrl>k__BackingField")]
        public static extern ref string SourceUrl(Recipe @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SyncId>k__BackingField")]
        public static extern ref Guid SyncId(Recipe @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Title>k__BackingField")]
        public static extern ref string Title(Recipe @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TotalTimeSeconds>k__BackingField")]
        public static extern ref decimal? TotalTimeSeconds(Recipe @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Bean>k__BackingField")]
        public static extern ref Bean Bean(Recipe @this);
    }
}
