// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using BaristaNotes.Core.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BaristaNotes.Core.Data.CompiledModels;

public static class ShotEquipmentUnsafeAccessors
{
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ShotRecordId>k__BackingField")]
    public static extern ref int ShotRecordId(ShotEquipment @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EquipmentId>k__BackingField")]
    public static extern ref int EquipmentId(ShotEquipment @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Equipment>k__BackingField")]
    public static extern ref Equipment Equipment(ShotEquipment @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ShotRecord>k__BackingField")]
    public static extern ref ShotRecord ShotRecord(ShotEquipment @this);
}
