// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using BaristaNotes.Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BaristaNotes.Core.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ShotEquipmentEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "BaristaNotes.Core.Models.ShotEquipment",
                typeof(ShotEquipment),
                baseEntityType,
                propertyCount: 2,
                navigationCount: 2,
                foreignKeyCount: 2,
                unnamedIndexCount: 1,
                keyCount: 1);

            var shotRecordId = runtimeEntityType.AddProperty(
                "ShotRecordId",
                typeof(int),
                propertyInfo: typeof(ShotEquipment).GetProperty("ShotRecordId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ShotEquipment).GetField("<ShotRecordId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            shotRecordId.SetGetter(
                int (ShotEquipment instance) => ShotEquipmentUnsafeAccessors.ShotRecordId(instance),
                bool (ShotEquipment instance) => ShotEquipmentUnsafeAccessors.ShotRecordId(instance) == 0);
            shotRecordId.SetSetter(
                ShotEquipment (ShotEquipment instance, int value) =>
                {
                    ShotEquipmentUnsafeAccessors.ShotRecordId(instance) = value;
                    return instance;
                });
            shotRecordId.SetMaterializationSetter(
                ShotEquipment (ShotEquipment instance, int value) =>
                {
                    ShotEquipmentUnsafeAccessors.ShotRecordId(instance) = value;
                    return instance;
                });
            shotRecordId.SetAccessors(
                int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<int>(0) : (entry.FlaggedAsTemporary(0) && ShotEquipmentUnsafeAccessors.ShotRecordId(((ShotEquipment)(entry.Entity))) == 0 ? entry.ReadTemporaryValue<int>(0) : ShotEquipmentUnsafeAccessors.ShotRecordId(((ShotEquipment)(entry.Entity))))),
                int (IInternalEntry entry) => ShotEquipmentUnsafeAccessors.ShotRecordId(((ShotEquipment)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(shotRecordId, 0),
                int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(shotRecordId, 0));
            shotRecordId.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            shotRecordId.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            shotRecordId.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(shotRecordId));

            var equipmentId = runtimeEntityType.AddProperty(
                "EquipmentId",
                typeof(int),
                propertyInfo: typeof(ShotEquipment).GetProperty("EquipmentId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ShotEquipment).GetField("<EquipmentId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            equipmentId.SetGetter(
                int (ShotEquipment instance) => ShotEquipmentUnsafeAccessors.EquipmentId(instance),
                bool (ShotEquipment instance) => ShotEquipmentUnsafeAccessors.EquipmentId(instance) == 0);
            equipmentId.SetSetter(
                ShotEquipment (ShotEquipment instance, int value) =>
                {
                    ShotEquipmentUnsafeAccessors.EquipmentId(instance) = value;
                    return instance;
                });
            equipmentId.SetMaterializationSetter(
                ShotEquipment (ShotEquipment instance, int value) =>
                {
                    ShotEquipmentUnsafeAccessors.EquipmentId(instance) = value;
                    return instance;
                });
            equipmentId.SetAccessors(
                int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(1) ? entry.ReadStoreGeneratedValue<int>(1) : (entry.FlaggedAsTemporary(1) && ShotEquipmentUnsafeAccessors.EquipmentId(((ShotEquipment)(entry.Entity))) == 0 ? entry.ReadTemporaryValue<int>(1) : ShotEquipmentUnsafeAccessors.EquipmentId(((ShotEquipment)(entry.Entity))))),
                int (IInternalEntry entry) => ShotEquipmentUnsafeAccessors.EquipmentId(((ShotEquipment)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(equipmentId, 1),
                int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(equipmentId, 1));
            equipmentId.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: 1);
            equipmentId.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            equipmentId.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(equipmentId));

            var key = runtimeEntityType.AddKey(
                new[] { shotRecordId, equipmentId });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { equipmentId });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("EquipmentId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            var equipment = declaringEntityType.AddNavigation("Equipment",
                runtimeForeignKey,
                onDependent: true,
                typeof(Equipment),
                propertyInfo: typeof(ShotEquipment).GetProperty("Equipment", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ShotEquipment).GetField("<Equipment>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            equipment.SetGetter(
                Equipment (ShotEquipment instance) => ShotEquipmentUnsafeAccessors.Equipment(instance),
                bool (ShotEquipment instance) => ShotEquipmentUnsafeAccessors.Equipment(instance) == null);
            equipment.SetSetter(
                ShotEquipment (ShotEquipment instance, Equipment value) =>
                {
                    ShotEquipmentUnsafeAccessors.Equipment(instance) = value;
                    return instance;
                });
            equipment.SetMaterializationSetter(
                ShotEquipment (ShotEquipment instance, Equipment value) =>
                {
                    ShotEquipmentUnsafeAccessors.Equipment(instance) = value;
                    return instance;
                });
            equipment.SetAccessors(
                Equipment (IInternalEntry entry) => ShotEquipmentUnsafeAccessors.Equipment(((ShotEquipment)(entry.Entity))),
                Equipment (IInternalEntry entry) => ShotEquipmentUnsafeAccessors.Equipment(((ShotEquipment)(entry.Entity))),
                null,
                Equipment (IInternalEntry entry) => entry.GetCurrentValue<Equipment>(equipment));
            equipment.SetPropertyIndexes(
                index: 0,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 2,
                storeGenerationIndex: -1);
            var shotEquipments = principalEntityType.AddNavigation("ShotEquipments",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<ShotEquipment>),
                propertyInfo: typeof(Equipment).GetProperty("ShotEquipments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Equipment).GetField("<ShotEquipments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            shotEquipments.SetGetter(
                ICollection<ShotEquipment> (Equipment instance) => EquipmentUnsafeAccessors.ShotEquipments(instance),
                bool (Equipment instance) => EquipmentUnsafeAccessors.ShotEquipments(instance) == null);
            shotEquipments.SetSetter(
                Equipment (Equipment instance, ICollection<ShotEquipment> value) =>
                {
                    EquipmentUnsafeAccessors.ShotEquipments(instance) = value;
                    return instance;
                });
            shotEquipments.SetMaterializationSetter(
                Equipment (Equipment instance, ICollection<ShotEquipment> value) =>
                {
                    EquipmentUnsafeAccessors.ShotEquipments(instance) = value;
                    return instance;
                });
            shotEquipments.SetAccessors(
                ICollection<ShotEquipment> (IInternalEntry entry) => EquipmentUnsafeAccessors.ShotEquipments(((Equipment)(entry.Entity))),
                ICollection<ShotEquipment> (IInternalEntry entry) => EquipmentUnsafeAccessors.ShotEquipments(((Equipment)(entry.Entity))),
                null,
                ICollection<ShotEquipment> (IInternalEntry entry) => entry.GetCurrentValue<ICollection<ShotEquipment>>(shotEquipments));
            shotEquipments.SetPropertyIndexes(
                index: 0,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: -1);
            shotEquipments.SetCollectionAccessor<Equipment, ICollection<ShotEquipment>, ShotEquipment>(
                ICollection<ShotEquipment> (Equipment entity) => EquipmentUnsafeAccessors.ShotEquipments(entity),
                (Equipment entity, ICollection<ShotEquipment> collection) => EquipmentUnsafeAccessors.ShotEquipments(entity) = ((ICollection<ShotEquipment>)collection),
                (Equipment entity, ICollection<ShotEquipment> collection) => EquipmentUnsafeAccessors.ShotEquipments(entity) = ((ICollection<ShotEquipment>)collection),
                ICollection<ShotEquipment> (Equipment entity, Action<Equipment, ICollection<ShotEquipment>> setter) => ClrCollectionAccessorFactory.CreateAndSetHashSet<Equipment, ICollection<ShotEquipment>, ShotEquipment>(entity, setter),
                ICollection<ShotEquipment> () => ((ICollection<ShotEquipment>)(((ICollection<ShotEquipment>)(new HashSet<ShotEquipment>(ReferenceEqualityComparer.Instance))))));
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ShotRecordId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            var shotRecord = declaringEntityType.AddNavigation("ShotRecord",
                runtimeForeignKey,
                onDependent: true,
                typeof(ShotRecord),
                propertyInfo: typeof(ShotEquipment).GetProperty("ShotRecord", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ShotEquipment).GetField("<ShotRecord>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            shotRecord.SetGetter(
                ShotRecord (ShotEquipment instance) => ShotEquipmentUnsafeAccessors.ShotRecord(instance),
                bool (ShotEquipment instance) => ShotEquipmentUnsafeAccessors.ShotRecord(instance) == null);
            shotRecord.SetSetter(
                ShotEquipment (ShotEquipment instance, ShotRecord value) =>
                {
                    ShotEquipmentUnsafeAccessors.ShotRecord(instance) = value;
                    return instance;
                });
            shotRecord.SetMaterializationSetter(
                ShotEquipment (ShotEquipment instance, ShotRecord value) =>
                {
                    ShotEquipmentUnsafeAccessors.ShotRecord(instance) = value;
                    return instance;
                });
            shotRecord.SetAccessors(
                ShotRecord (IInternalEntry entry) => ShotEquipmentUnsafeAccessors.ShotRecord(((ShotEquipment)(entry.Entity))),
                ShotRecord (IInternalEntry entry) => ShotEquipmentUnsafeAccessors.ShotRecord(((ShotEquipment)(entry.Entity))),
                null,
                ShotRecord (IInternalEntry entry) => entry.GetCurrentValue<ShotRecord>(shotRecord));
            shotRecord.SetPropertyIndexes(
                index: 1,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 3,
                storeGenerationIndex: -1);
            var shotEquipments = principalEntityType.AddNavigation("ShotEquipments",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<ShotEquipment>),
                propertyInfo: typeof(ShotRecord).GetProperty("ShotEquipments", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ShotRecord).GetField("<ShotEquipments>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            shotEquipments.SetGetter(
                ICollection<ShotEquipment> (ShotRecord instance) => ShotRecordUnsafeAccessors.ShotEquipments(instance),
                bool (ShotRecord instance) => ShotRecordUnsafeAccessors.ShotEquipments(instance) == null);
            shotEquipments.SetSetter(
                ShotRecord (ShotRecord instance, ICollection<ShotEquipment> value) =>
                {
                    ShotRecordUnsafeAccessors.ShotEquipments(instance) = value;
                    return instance;
                });
            shotEquipments.SetMaterializationSetter(
                ShotRecord (ShotRecord instance, ICollection<ShotEquipment> value) =>
                {
                    ShotRecordUnsafeAccessors.ShotEquipments(instance) = value;
                    return instance;
                });
            shotEquipments.SetAccessors(
                ICollection<ShotEquipment> (IInternalEntry entry) => ShotRecordUnsafeAccessors.ShotEquipments(((ShotRecord)(entry.Entity))),
                ICollection<ShotEquipment> (IInternalEntry entry) => ShotRecordUnsafeAccessors.ShotEquipments(((ShotRecord)(entry.Entity))),
                null,
                ICollection<ShotEquipment> (IInternalEntry entry) => entry.GetCurrentValue<ICollection<ShotEquipment>>(shotEquipments));
            shotEquipments.SetPropertyIndexes(
                index: 5,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 11,
                storeGenerationIndex: -1);
            shotEquipments.SetCollectionAccessor<ShotRecord, ICollection<ShotEquipment>, ShotEquipment>(
                ICollection<ShotEquipment> (ShotRecord entity) => ShotRecordUnsafeAccessors.ShotEquipments(entity),
                (ShotRecord entity, ICollection<ShotEquipment> collection) => ShotRecordUnsafeAccessors.ShotEquipments(entity) = ((ICollection<ShotEquipment>)collection),
                (ShotRecord entity, ICollection<ShotEquipment> collection) => ShotRecordUnsafeAccessors.ShotEquipments(entity) = ((ICollection<ShotEquipment>)collection),
                ICollection<ShotEquipment> (ShotRecord entity, Action<ShotRecord, ICollection<ShotEquipment>> setter) => ClrCollectionAccessorFactory.CreateAndSetHashSet<ShotRecord, ICollection<ShotEquipment>, ShotEquipment>(entity, setter),
                ICollection<ShotEquipment> () => ((ICollection<ShotEquipment>)(((ICollection<ShotEquipment>)(new HashSet<ShotEquipment>(ReferenceEqualityComparer.Instance))))));
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var shotRecordId = runtimeEntityType.FindProperty("ShotRecordId");
            var equipmentId = runtimeEntityType.FindProperty("EquipmentId");
            var key = runtimeEntityType.FindKey(new[] { shotRecordId, equipmentId });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateCompositeFactory(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<IReadOnlyList<object>>(key));
            var equipment = runtimeEntityType.FindNavigation("Equipment");
            var shotRecord = runtimeEntityType.FindNavigation("ShotRecord");
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((ShotEquipment)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, int>(((ValueComparer<int>)(((IProperty)shotRecordId).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(shotRecordId)), ((ValueComparer<int>)(((IProperty)equipmentId).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(equipmentId)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<int, int>(((ValueComparer<int>)(((IProperty)shotRecordId).GetValueComparer())).Snapshot(default(int)), ((ValueComparer<int>)(((IProperty)equipmentId).GetValueComparer())).Snapshot(default(int))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<int, int>(default(int), default(int)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((ShotEquipment)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, int, object, object>(((ValueComparer<int>)(((IProperty)shotRecordId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(shotRecordId)), ((ValueComparer<int>)(((IProperty)equipmentId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(equipmentId)), source.GetCurrentValue<Equipment>(equipment), source.GetCurrentValue<ShotRecord>(shotRecord))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 2,
                navigationCount: 2,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 2,
                shadowCount: 0,
                relationshipCount: 4,
                storeGeneratedCount: 2));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "ShotEquipments");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
