// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using BaristaNotes.Core.Models;
using BaristaNotes.Core.Models.Enums;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BaristaNotes.Core.Data.CompiledModels;

public static class ShotRecordUnsafeAccessors
{
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
    public static extern ref int Id(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ActualOutput>k__BackingField")]
    public static extern ref decimal? ActualOutput(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ActualTime>k__BackingField")]
    public static extern ref decimal? ActualTime(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BagId>k__BackingField")]
    public static extern ref int BagId(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BrewMethod>k__BackingField")]
    public static extern ref BrewMethod BrewMethod(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DoseIn>k__BackingField")]
    public static extern ref decimal DoseIn(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DrinkType>k__BackingField")]
    public static extern ref string DrinkType(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ExpectedOutput>k__BackingField")]
    public static extern ref decimal ExpectedOutput(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ExpectedTime>k__BackingField")]
    public static extern ref decimal ExpectedTime(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<GrindMicrons>k__BackingField")]
    public static extern ref int? GrindMicrons(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<GrinderId>k__BackingField")]
    public static extern ref int? GrinderId(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsDeleted>k__BackingField")]
    public static extern ref bool IsDeleted(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastModifiedAt>k__BackingField")]
    public static extern ref DateTime LastModifiedAt(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MachineId>k__BackingField")]
    public static extern ref int? MachineId(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MadeById>k__BackingField")]
    public static extern ref int? MadeById(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MadeForId>k__BackingField")]
    public static extern ref int? MadeForId(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ParametersJson>k__BackingField")]
    public static extern ref string ParametersJson(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PreinfusionTime>k__BackingField")]
    public static extern ref decimal? PreinfusionTime(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Rating>k__BackingField")]
    public static extern ref int? Rating(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SyncId>k__BackingField")]
    public static extern ref Guid SyncId(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TastingNotes>k__BackingField")]
    public static extern ref string TastingNotes(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Timestamp>k__BackingField")]
    public static extern ref DateTime Timestamp(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<WaterTempC>k__BackingField")]
    public static extern ref decimal? WaterTempC(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Bag>k__BackingField")]
    public static extern ref Bag Bag(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Grinder>k__BackingField")]
    public static extern ref Equipment Grinder(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Machine>k__BackingField")]
    public static extern ref Equipment Machine(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MadeBy>k__BackingField")]
    public static extern ref UserProfile MadeBy(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MadeFor>k__BackingField")]
    public static extern ref UserProfile MadeFor(ShotRecord @this);

    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ShotEquipments>k__BackingField")]
    public static extern ref ICollection<ShotEquipment> ShotEquipments(ShotRecord @this);
}
