// <auto-generated />
using System;
using BaristaNotes.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaristaNotes.Core.Migrations
{
    [DbContext(typeof(BaristaNotesContext))]
    [Migration("20251206024345_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("BaristaNotes.Core.Models.Bean", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RoastDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Roaster")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("SyncId")
                        .IsUnique();

                    b.HasIndex("Name", "Roaster");

                    b.ToTable("Beans");
                });

            modelBuilder.Entity("BaristaNotes.Core.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("SyncId")
                        .IsUnique();

                    b.HasIndex("Name", "Type");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("BaristaNotes.Core.Models.ShotEquipment", b =>
                {
                    b.Property<int>("ShotRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ShotRecordId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("ShotEquipments");
                });

            modelBuilder.Entity("BaristaNotes.Core.Models.ShotRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ActualOutput")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ActualTime")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BeanId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DoseIn")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("DrinkType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedOutput")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedTime")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("GrindSetting")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("GrinderId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MadeById")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MadeForId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PreinfusionTime")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeanId");

                    b.HasIndex("GrinderId");

                    b.HasIndex("MachineId");

                    b.HasIndex("MadeById");

                    b.HasIndex("MadeForId");

                    b.HasIndex("SyncId")
                        .IsUnique();

                    b.HasIndex("Timestamp")
                        .IsDescending();

                    b.ToTable("ShotRecords");
                });

            modelBuilder.Entity("BaristaNotes.Core.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("SyncId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("BaristaNotes.Core.Models.ShotEquipment", b =>
                {
                    b.HasOne("BaristaNotes.Core.Models.Equipment", "Equipment")
                        .WithMany("ShotEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaristaNotes.Core.Models.ShotRecord", "ShotRecord")
                        .WithMany("ShotEquipments")
                        .HasForeignKey("ShotRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("ShotRecord");
                });

            modelBuilder.Entity("BaristaNotes.Core.Models.ShotRecord", b =>
                {
                    b.HasOne("BaristaNotes.Core.Models.Bean", "Bean")
                        .WithMany("ShotRecords")
                        .HasForeignKey("BeanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BaristaNotes.Core.Models.Equipment", "Grinder")
                        .WithMany()
                        .HasForeignKey("GrinderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BaristaNotes.Core.Models.Equipment", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BaristaNotes.Core.Models.UserProfile", "MadeBy")
                        .WithMany("ShotsMadeBy")
                        .HasForeignKey("MadeById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BaristaNotes.Core.Models.UserProfile", "MadeFor")
                        .WithMany("ShotsMadeFor")
                        .HasForeignKey("MadeForId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bean");

                    b.Navigation("Grinder");

                    b.Navigation("Machine");

                    b.Navigation("MadeBy");

                    b.Navigation("MadeFor");
                });

            modelBuilder.Entity("BaristaNotes.Core.Models.Bean", b =>
                {
                    b.Navigation("ShotRecords");
                });

            modelBuilder.Entity("BaristaNotes.Core.Models.Equipment", b =>
                {
                    b.Navigation("ShotEquipments");
                });

            modelBuilder.Entity("BaristaNotes.Core.Models.ShotRecord", b =>
                {
                    b.Navigation("ShotEquipments");
                });

            modelBuilder.Entity("BaristaNotes.Core.Models.UserProfile", b =>
                {
                    b.Navigation("ShotsMadeBy");

                    b.Navigation("ShotsMadeFor");
                });
#pragma warning restore 612, 618
        }
    }
}
